### ISSUE TITLE
Suggestion  Change color of notification info

### ISSUE THREAD

**Issue by xpt1x** [vinceliuice/Orchis-theme#10]
![image](https://user-images.githubusercontent.com/33655587/81378943-d618fa00-9125-11ea-9a90-0ef715c21674.png)

While playing from Spotify notification is appearing like this, with Artist name in proper white color but song's name in dark, which is annoying to read
Should be changed to -> White

**Comment by vinceliuice** [comment]
Did you install this theme from here, this is fixed

**Comment by xpt1x** [comment]
Ok i m trying this from ur latest commit now, will let u knw

**Comment by xpt1x** [comment]
Yeah its fixed !
Thanks @vinceliuice
