### ISSUE TITLE
Filenames of selected items are hard to read when they overlap another icon.

### ISSUE THREAD

**Issue by LeFloatyPancake** [vinceliuice/Orchis-theme#101]
I came across this issue when I tried accessing a video library with long file names. As you can see in the screenshot below, the transparency of the background when a file is selected is too high. I visited your other themes like Whitesur and found that the background color is opaque. Also tried the default Adwaita theme which gave the same opaque background. 

![File names](https://user-images.githubusercontent.com/83509112/120987172-ed566b00-c7af-11eb-8b35-1468c493ca55.png)

A possible solution might be to copy the color from the status line at the bottom of the file manager. This would greatly benefit readability.

Edit: Nautilus ver 40.2

**Comment by vinceliuice** [comment]
I'll fix this
