### ISSUE TITLE
Events, world clock, and weather background box "cut-off" in popover menu

### ISSUE THREAD

**Issue by LeFloatyPancake** [vinceliuice/Orchis-theme#104]
Gnome 40

First of all, I just want to say thanks for creating such a beautiful theme.

I've discovered a visual bug related to the top panel specifically the popover menu for the date and time. As you can see in the screenshots below, the "container" or text background for events, and clock are seemingly cut-off (this also happens with the weather container but I did not include it here). The corners at the right most end of the container aren't rounded like they are in the non-compact/standard variants.

This test is based on commit 6cb1be9 

![popover](https://user-images.githubusercontent.com/83509112/121338711-570d7b00-c950-11eb-8bed-c9fe6b6ac59f.png)

Oh and an extra question. Will you be offering a solid shell theme for both light and dark variants?

**Comment by vinceliuice** [comment]
Didn't notice that before since I enabled week numbers, I'll fix this!

**Comment by 64542426** [comment]
This issue still persist for me on GNOME 42.0 (Wayland). Please activate World Clock and Weather we'll see the text of world clock and weather image icons are cropped. Adwaita or other themes doesn't have this matter.
