### ISSUE TITLE
default option not working for installation directory ```/usr/share/themes/``` 

### ISSUE THREAD

**Issue by Amit0617** [vinceliuice/Orchis-theme#115]
i tried without using ```-d /usr/share/themes/``` and it shows output for installation in terminal as it should be but orchis is not showing up in ```/usr/share/themes/``` directory. As a result it is not showing up in "Tweaks tool". Hence, it is must to use that command for make it effective.

**Comment by vinceliuice** [comment]
Just run `sudo ./install.sh`

**Comment by Amit0617** [comment]
Oh that sudo!😅
