### ISSUE TITLE
can't make gnome shell panel compact in ubuntu 20.04

### ISSUE THREAD

**Issue by akashsinhaha** [vinceliuice/Orchis-theme#117]
it doesn't look good with the padding 
i also tried doing ./install.sh --tweaks compact

here is a screenshot 

![Screenshot from 2021-07-07 00-27-14](https://user-images.githubusercontent.com/73224793/124652916-50741400-deba-11eb-912e-55d1e9700b22.png)

**Comment by akashsinhaha** [comment]
Not working

**Comment by vinceliuice** [comment]
The last update still not working？
