### ISSUE TITLE
Flatpak theme?

### ISSUE THREAD

**Issue by Icy-Thought** [vinceliuice/Orchis-theme#12]
Has there been any thoughts regarding porting this theme to flatpak? Having flatpak installed packages theme like the rest of the native installed packages would be wonderful! :smile_cat:

**Comment by matfantinel** [comment]
You can make Flatpak read themes from other folders, which makes this theme work on the packages through the command line.

If Flatpak is installed as user (you can use `flatpak list` and check the last column of the results to see if it's "user" or "system")
`flatpak override --user --filesystem=~/.themes`

If it's system:
`sudo flatpak override --filesystem=~/.themes`

**Comment by Icy-Thought** [comment]
Apparently I should've browsed more efficient because that search result was not part of the listed solutions to this issue. Thank you!
