### ISSUE TITLE
stylesheet.css not exist!

### ISSUE THREAD

**Issue by andikatuluspangestu** [vinceliuice/Orchis-theme#120]
After run command ./install.sh in path .themes/Orchis-theme/src/gnome-shell/extensions/workspaces-to-dock ..

Output :

`stylesheet.css not exist!`

**Comment by vinceliuice** [comment]
Why run in workspaces-to-dock?

**Comment by andikatuluspangestu** [comment]
> Why run in workspaces-to-dock?

Ahh, yea sorry.. I mean `$.themes/Orchis-theme/src/gnome-shell/extensions/dash-to-panel`

**Comment by vinceliuice** [comment]
Where did you installed dash-to-panel?

**Comment by vinceliuice** [comment]
If you installed in system dir, then run sudo ./install.sh

**Comment by andikatuluspangestu** [comment]
> Where did you installed dash-to-panel?

![Screenshot from 2021-07-12 11-05-36](https://user-images.githubusercontent.com/62005221/125229754-9a695980-e301-11eb-8d72-938cd7e47eb0.png)

**Comment by vinceliuice** [comment]
Did you installed dash-to-panel?

**Comment by vinceliuice** [comment]
And Don't put the source folder into .theme foder, just run ./install.sh to install into .theme

**Comment by andikatuluspangestu** [comment]
> And Don't put the source folder into .theme foder, just run ./install.sh to install into .theme

Wokkey, thanks bru.. fixed
