### ISSUE TITLE
Notification edges look weird/broken on GNOME 40.2

### ISSUE THREAD

**Issue by niklasstich** [vinceliuice/Orchis-theme#121]
![notif_edges](https://user-images.githubusercontent.com/32730297/125719370-ac8bb7ab-832b-4bb4-9740-5670ab49a193.png)
As you can see, there seems to be a transparency issue of some sort on the edges of the notification boxes.
Manjaro Linux, GNOME 40.2, installed newest version of the theme manually via `./install.sh`

Thanks for your great theme!

**Comment by vinceliuice** [comment]
![Screenshot from 2021-07-15 12-56-19](https://user-images.githubusercontent.com/7604295/125730997-0a87a8ee-04fa-4f51-a422-84528bd692b0.png)

**Comment by vinceliuice** [comment]
I did not have this issue

**Comment by vinceliuice** [comment]
![Screenshot from 2021-07-15 12-59-32](https://user-images.githubusercontent.com/7604295/125731246-a6e62180-8967-443a-a707-6ff6ee0085f7.png)

**Comment by niklasstich** [comment]
![adwaita](https://user-images.githubusercontent.com/32730297/125811223-b3596d8c-e57c-4e5c-93c4-d5dc3320abf2.png)
Adwaita Theme for example works properly for me. Just tried some different colors, compact and dark and they all seem to have the same issue for me. Anything you would like me to send or do for debug purposes?

**Comment by vinceliuice** [comment]
Did you changed the system default gnome-shell theme？

**Comment by niklasstich** [comment]
![image](https://user-images.githubusercontent.com/32730297/125968162-baec56cc-89ba-43fe-bfcf-a63b04a9b8d3.png)
I've set it here in Gnome Tweaks. I've looked through the GNOME Settings window but couldn't find any other relevant settings.
![image](https://user-images.githubusercontent.com/32730297/125968852-3d5f05a6-d59a-4118-a638-2c14edbbd3f9.png)
Also here is my list of active extensions. I've already tried disabling all of them and restarting but no luck there either.

**Comment by vinceliuice** [comment]
Fixed!

**Comment by niklasstich** [comment]
Fixed! Thanks very much for your work!

**Comment by vinceliuice** [comment]
You are welcome!
