### ISSUE TITLE
Text does not fit in GTK4 header bar buttons

### ISSUE THREAD

**Issue by ExposedCat** [vinceliuice/Orchis-theme#123]
In GNOME System Monitor, header bar buttons became small so text is not fit
**Adwaita dark**:
![image](https://user-images.githubusercontent.com/44642024/125947615-e8ef5687-7092-4a3a-93f8-7b02eaef2a77.png)
**Orchis dark**:
![image](https://user-images.githubusercontent.com/44642024/125947695-1226d6c0-0c54-483b-b426-2ad599bb5ad9.png)

btw, the whole title bar looks taller than in Adwaita

**Comment by vinceliuice** [comment]
No problem! I'll fix this!

**Comment by vinceliuice** [comment]
Fixed!

**Comment by ExposedCat** [comment]
@vinceliuice thx!
Btw, may I ask you how to reduce headerbars (csd) height?

**Comment by vinceliuice** [comment]
Why not use the compact version?
