### ISSUE TITLE
Nautilus not styled properly with --solid argument

### ISSUE THREAD

**Issue by nikbott** [vinceliuice/Orchis-theme#124]
GNOME 40.3
Repo cloned from github and 

`./install.sh -d ~/.local/share/themes/ -c dark --tweaks solid --tweaks compact`

![Screenshot from 2021-07-16 21-06-33](https://user-images.githubusercontent.com/71557664/126019175-f34827c6-0392-4efb-a6f6-50357519d06c.png)

**Comment by vinceliuice** [comment]
I do not get this？ what's the issue？

**Comment by nikbott** [comment]
Well, isn't it supposed to have just one color? Or does it only remove transparency?

**Comment by vinceliuice** [comment]
You mean the panel background color? I'll fix this
