### ISSUE TITLE
how to install all themes (old option -t all)

### ISSUE THREAD

**Issue by ChrisLauinger77** [vinceliuice/Orchis-theme#126]
I tried 
./install.sh --dest ~/.themes -t default purple pink red orange yellow green grey

The output is like following:
`./install.sh --dest ~/.themes -t default purple pink red orange yellow green grey
Install grey color version ...
Installing '/home/christian/.themes/Orchis'...
Installing '/home/christian/.themes/Orchis-compact'...
Installing '/home/christian/.themes/Orchis-light'...
Installing '/home/christian/.themes/Orchis-light-compact'...
Installing '/home/christian/.themes/Orchis-dark'...
Installing '/home/christian/.themes/Orchis-dark-compact'...
Installing '/home/christian/.themes/Orchis-purple'...
Installing '/home/christian/.themes/Orchis-purple-compact'...
Installing '/home/christian/.themes/Orchis-purple-light'...
Installing '/home/christian/.themes/Orchis-purple-light-compact'...
Installing '/home/christian/.themes/Orchis-purple-dark'...
Installing '/home/christian/.themes/Orchis-purple-dark-compact'...
Installing '/home/christian/.themes/Orchis-pink'...
Installing '/home/christian/.themes/Orchis-pink-compact'...
Installing '/home/christian/.themes/Orchis-pink-light'...
Installing '/home/christian/.themes/Orchis-pink-light-compact'...
Installing '/home/christian/.themes/Orchis-pink-dark'...
Installing '/home/christian/.themes/Orchis-pink-dark-compact'...
Installing '/home/christian/.themes/Orchis-red'...
Installing '/home/christian/.themes/Orchis-red-compact'...
Installing '/home/christian/.themes/Orchis-red-light'...
Installing '/home/christian/.themes/Orchis-red-light-compact'...
Installing '/home/christian/.themes/Orchis-red-dark'...
Installing '/home/christian/.themes/Orchis-red-dark-compact'...
Installing '/home/christian/.themes/Orchis-orange'...
Installing '/home/christian/.themes/Orchis-orange-compact'...
Installing '/home/christian/.themes/Orchis-orange-light'...
Installing '/home/christian/.themes/Orchis-orange-light-compact'...
Installing '/home/christian/.themes/Orchis-orange-dark'...
Installing '/home/christian/.themes/Orchis-orange-dark-compact'...
Installing '/home/christian/.themes/Orchis-yellow'...
Installing '/home/christian/.themes/Orchis-yellow-compact'...
Installing '/home/christian/.themes/Orchis-yellow-light'...
Installing '/home/christian/.themes/Orchis-yellow-light-compact'...
Installing '/home/christian/.themes/Orchis-yellow-dark'...
Installing '/home/christian/.themes/Orchis-yellow-dark-compact'...
Installing '/home/christian/.themes/Orchis-green'...
Installing '/home/christian/.themes/Orchis-green-compact'...
Installing '/home/christian/.themes/Orchis-green-light'...
Installing '/home/christian/.themes/Orchis-green-light-compact'...
Installing '/home/christian/.themes/Orchis-green-dark'...
Installing '/home/christian/.themes/Orchis-green-dark-compact'...
Installing '/home/christian/.themes/Orchis-grey'...
Installing '/home/christian/.themes/Orchis-grey-compact'...
Installing '/home/christian/.themes/Orchis-grey-light'...
Installing '/home/christian/.themes/Orchis-grey-light-compact'...
Installing '/home/christian/.themes/Orchis-grey-dark'...
Installing '/home/christian/.themes/Orchis-grey-dark-compact'...
Restore _tweaks.scss file ...

Done.`

BUt all installed themes are grey :(

**Comment by vinceliuice** [comment]
Run `./install-all.sh` now
