### ISSUE TITLE
Gnome shell isn't displaying correctly

### ISSUE THREAD

**Issue by JuanLiz** [vinceliuice/Orchis-theme#127]
Since the last update the theme does not display correctly in GNOME Shell
![Captura de pantalla de 2021-07-21 23-46-52](https://user-images.githubusercontent.com/47019693/126591159-cfebeb63-4964-45ad-b524-db550f09872c.png)
![Captura de pantalla de 2021-07-21 23-46-49](https://user-images.githubusercontent.com/47019693/126591164-183f2265-b31e-4a28-8e81-dd6156edd5f2.png)

**Comment by BussdriverOMG** [comment]
Manjaro Gnome
cat /etc/lsb-release
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.1.0
DISTRIB_CODENAME=Pahvo
DISTRIB_DESCRIPTION="Manjaro Linux"
gnome-shell --version = GNOME Shell 40.3

![shadow](https://user-images.githubusercontent.com/73340504/130631157-58a67824-a82c-4c4f-ac0b-c045b51908ba.png)
