### ISSUE TITLE
Ubuntu Software won't switch to dark theme

### ISSUE THREAD

**Issue by ganeshkalyank** [vinceliuice/Orchis-theme#134]
When I select Yaru dark, Ubuntu Software is switching to dark version. But, with Orchis-dark-compact, it remains light. I won't use Ubuntu Software except for Blender update. But, this issue should be solved as it effects other users who use it regularly.

![Screenshot from 2021-07-30 10-29-55](https://user-images.githubusercontent.com/55980110/127602859-7f188890-a929-482b-8d6b-e983614eb9ba.png)
![Screenshot from 2021-07-30 10-30-41](https://user-images.githubusercontent.com/55980110/127602887-af5ccc76-9c27-4259-91db-047e2c9a4800.png)

**Comment by vinceliuice** [comment]
Install snap version: https://snapcraft.io/orchis-themes
