### ISSUE TITLE
Dark theme blue accent shows green radio buttons

### ISSUE THREAD

**Issue by zachbryant** [vinceliuice/Orchis-theme#138]
Selected theme accent is blue, but I'm seeing green radio buttons.

![Screenshot from 2021-08-18 12-59-54](https://user-images.githubusercontent.com/32501288/129964551-092be726-3e27-4f8d-8a31-790d2ebae6d7.png)

**Comment by vinceliuice** [comment]
run `./install.sh --tweaks primary`

**Comment by vinceliuice** [comment]
Default is all use green radio button

**Comment by zachbryant** [comment]
I see, this requires some re-downloading as I used ocs-url in gnome-look and it didn't include `install.sh`. Perhaps it can be updated to include the file?

**Comment by zachbryant** [comment]
I ran manual installation and that command led to the same bug

**Comment by zachbryant** [comment]
Fixed!
