### ISSUE TITLE
Too much padding with Cinnamon

### ISSUE THREAD

**Issue by ryaniskira** [vinceliuice/Orchis-theme#141]
**DE:** Cinnamon
**OS:** Arch
**Source:** [AUR](https://aur.archlinux.org/packages/orchis-theme-git/)

There's a bit too much padding on Cinnamon Panel's right zone. This happens when you set Orchis as the "desktop" theme in Cinnamon's theme settings.

Materia:
![](https://i.postimg.cc/FzFH3n3J/Screenshot-from-2021-09-14-20-58-31.png)

Orchis:
![](https://i.postimg.cc/bwnpDjWB/Screenshot-from-2021-09-14-20-58-14.png)

**Comment by ryaniskira** [comment]
I've actually fixed this issue by changing the applet separator and box padding from 8px to 4px. Would a PR be acceptable since this would only affect Cinnamon which is what is in need of the fix? 

```
.applet-separator {
  padding: 1px 4px;
}

.applet-separator-line {
  width: 1px;
  background: rgba(255, 255, 255, 0.12);
}

.applet-box {
  padding: 0 4px;
  color: rgba(255, 255, 255, 0.7);
  text-shadow: none;
  transition-duration: 100ms;
  border-radius: 0;
}
```

**Comment by vinceliuice** [comment]
No problem!

**Comment by ryaniskira** [comment]
I've submitted a PR with the fixes.
