### ISSUE TITLE
Gnome的panel显示出错

### ISSUE THREAD

**Issue by nerimoe** [vinceliuice/Orchis-theme#142]
![Screenshot from 2021-09-21 13-49-22](https://user-images.githubusercontent.com/57009175/134118762-09a5cef7-94cf-4aae-a9aa-dd611f88d5e8.png)
![Screenshot from 2021-09-21 13-49-44](https://user-images.githubusercontent.com/57009175/134118764-0e47c780-c508-48c8-a800-22c1c032f9e6.png)

如图，左边圆圈的间距消失，不连接WLAN的时候右边菜单和屏幕的间距会变得很大，clone下来后安装的主题。
gnome 40.4, 
archlinux, 
2560x1600

**Comment by vinceliuice** [comment]
修复了
