### ISSUE TITLE
OrchisDark - Main Menu - Sub Menu - box is white

### ISSUE THREAD

**Issue by Mapuut** [vinceliuice/Orchis-theme#145]
Running Ubuntu 21.04

Installed Orchis-theme using **install.sh**, both r**egular install** and **sudo**.
Changed **Application** and **Shell** themes to Orchies-dark in Gnome Tweaks.
Installed snap package and connected to everything.

![image](https://user-images.githubusercontent.com/35892391/135659804-080ed764-4f49-4192-9119-9190326f6880.png)

Everything seems to work well, except one single place - **sub-menu box** inside main menu. It is using Orchis-theme, has rounded corners and white theme colors. So it just seems that it was not overwritten for dark theme, either intentionally or by mistake.

![image](https://user-images.githubusercontent.com/35892391/135661018-4b5e3e6a-f62b-4ea6-abd3-d33191e49d9a.png)

It feels like mistake so I opened ticket. If I am wrong or just did something stupid feel free to close this issue.

**Comment by vinceliuice** [comment]
Deliberately designed like this, referring to Google’s chromeos style

**Comment by Mapuut** [comment]
Thank you for answer. Closing issue.

If somebody like me for some reason just doesn't like that white color and you happened to find this issue - here is some CSS that might save you couple of minutes.

![image](https://user-images.githubusercontent.com/35892391/135719713-a222a56e-3435-498b-9722-885e3d894aac.png)

Paste this CSS at the end of **gnome-shell.css** file located in your **home directory -> .themes/Orchis-dark/gnome-shell/**

```
/* ********************* */
/* + CUSTOM BEGIN*/
/* ********************* */
.popup-menu .popup-sub-menu {
  background-color: #2b2b36;
  color: rgba(255, 255, 255, 0.9);
}

.popup-menu .popup-sub-menu .popup-menu-item {
  color: rgba(255, 255, 255, 0.9);
}

.popup-menu .popup-menu-item {
  margin: 2px 6px;
  padding: 8px;
}

.popup-menu .popup-menu-item:checked {
  margin: 0px 6px;
  padding: 10px;
}

.popup-menu .popup-menu-item:ltr {
  padding-right: 1.8em;
  padding-left: 0;
}

.popup-menu StLabel {
  font-weight: 700 !important;
}

.popup-menu .popup-sub-menu StLabel {
  font-weight: 500 !important;
}

.popup-menu .popup-sub-menu .popup-menu-item:hover {
  color: rgba(255, 255, 255, 0.9);
  background-color: rgba(255, 255, 255, 0.15);
}

.popup-menu .popup-sub-menu .popup-menu-item:active {
  color: rgba(255, 255, 255, 0.9);
  background-color: rgba(255, 255, 255, 0.2);
}

.popup-menu .popup-sub-menu .popup-menu-item.selected:active {
  color: rgba(255, 255, 255, 0.9);
}

.popup-menu .popup-sub-menu .popup-menu-item:insensitive {
  color: rgba(255, 255, 255, 0.35);
}

.popup-menu .popup-menu-content {
  padding: 10px 5px 12px 8px;
}

.popup-menu .popup-menu-item:checked {
  background-color: #2b2b36;
  color: rgba(255, 255, 255, 0.9);
}

.popup-menu .popup-menu-item.selected:checked {
  background-color: #2b2b36;
  color: rgba(255, 255, 255, 0.9);
}

.popup-menu .popup-menu-item:checked:active {
  background-color: #2b2b36;
  color: rgba(255, 255, 255, 0.75);
}

.popup-menu .popup-menu-item.selected:checked:active {
  background-color: #2b2b36;
  color: rgba(255, 255, 255, 0.75);
}

.popup-menu .popup-menu-item:checked:insensitive {
  color: rgba(255, 255, 255, 0.35);
}

.popup-menu .popup-menu-item.selected {
  background-color: #2b2b36;
}

.popup-menu .popup-menu-item:active {
  background-color: #2b2b36;
  color: rgba(255, 255, 255, 0.9);
}

.popup-menu .popup-menu-item.selected:active {
  color: rgba(255, 255, 255, 0.75);
}

/* ********************* */
/* - CUSTOM END */
/* ********************* */
```
