### ISSUE TITLE
dock style problem in gnome 40 (2 dark backgrounds)

### ISSUE THREAD

**Issue by MelodyJoke** [vinceliuice/Orchis-theme#154]
there are 2 backgrounds. a darker one with corners and a lighter one. on ubuntu 21.10.
![2021-10-17 16-21-47 的屏幕截图](https://user-images.githubusercontent.com/16795037/137618558-c214953c-96a7-40e6-96c9-422e721eb4ce.png)

**Comment by vinceliuice** [comment]
没用什么其他插件吧，像blur my shell这种

**Comment by MelodyJoke** [comment]
我没有用过别的插件。启用的插件只有4个，desktop icons ng， ubuntu applicators, ubuntu dock 和 user themes。也不是很重要啦，21.10才出来两三天...

**Comment by Nirzak** [comment]
Same here. I was using this with ubuntu 20.04 but when I have upgraded to Ubuntu 21.10 the dock becomes too dark. Previously it was more transparent.

**Comment by Merlo17** [comment]
Is there a fix to this problem? I can't seem to solve it and I saw the issue was closed. I would like to get a fix if possible
