### ISSUE TITLE
Theme dock not working

### ISSUE THREAD

**Issue by soroshzzz26** [vinceliuice/Orchis-theme#161]
hi i installed the theme by instructions but the dock and topbar theme not applying 
please help me to solve this

im on ubuntu 20.0.4

**Comment by soroshzzz26** [comment]
that was my bad i should install the tweaks extensions
i will close the issue

**Comment by arhanjain** [comment]
hey @soroshzzz26 how did you get this to work? I'm definitely missing something, my dash-to-panel install says done and I reloaded GNOME but the theme hasn't applied. I'm also pretty new to linux so please excuse anything silly im doing.
![image](https://user-images.githubusercontent.com/43100506/149282179-cdf8eccb-8e34-46db-836a-5fe58eabea42.png)

**Comment by soroshzzz26** [comment]
@arhanjain hi I'm new to Linux too and I'm really confused when it's about theme installation and...
but I had the same problem and I installed "Gnome tweaks extensions" after restarting the system its started to work!

https://itsfoss.com/gnome-shell-extensions/
