### ISSUE TITLE
Bell Icon above No Notification in GNOME 41

### ISSUE THREAD

**Issue by Anifyuli** [vinceliuice/Orchis-theme#163]
Hello, Bro Vince.

I have a small problem in your designed theme. Same as title of this issue, I see a bug or error in your theme because bell icon above no notification has dissappear in my favorite GNOME DE and all of your theme (except Matcha due to Manjaro default theme). I want you to fix that problem. 

[https://forum.manjaro.org/uploads/default/optimized/3X/2/3/23c481a029d802461c1017caf8729ebf62eb0bc9_2_690x387.jpeg](url)

I wait your update on my Github timeline. I love this theme.

Thanks for your hardwork and favors. 

CMIIW, my English is bad

**Comment by Anifyuli** [comment]
My GNOME version is 41, Bro

**Comment by vinceliuice** [comment]
I did not find this issue on my desktop, did you changed the gdm theme?

**Comment by Anifyuli** [comment]
Yes, I change GDM theme with Orchis theme too. What's wrong with that action, Bro?
