### ISSUE TITLE
Dedebbianize the source folder

### ISSUE THREAD

**Issue by fossfreedom** [vinceliuice/Orchis-theme#164]
Its a little unusual to have in a theme source tree a debian folder (or indeed any other distro specific folder).

Any chance that this folder to be deleted - or at a minimum moved to its own empty debian branch?

I would like to package this theme for Ubuntu Budgie - but at the moment the debian folder clashes with our own package.

**Comment by vinceliuice** [comment]
No problem! I'll add it to a debain branch
