### ISSUE TITLE
Icons not available in tweaks icon settings

### ISSUE THREAD

**Issue by MacherelR** [vinceliuice/Orchis-theme#166]
I succesfully cloned the repo and launched the install.sh, this made the shell theme and app theme available on the tweaks app, but I can't find the Orchis icons in the related dropdown list... Any idea ?

**Comment by vinceliuice** [comment]
There is no orchis icon, I use tela-circle for this theme

**Comment by vinceliuice** [comment]
https://github.com/vinceliuice/Tela-circle-icon-theme

**Comment by MacherelR** [comment]
Ok my bad thanks for your answer ! (Closing this subject)
