### ISSUE TITLE
White background color instead of black in power/network etc. dropdown menus (Ubuntu 20.04)

### ISSUE THREAD

**Issue by BonaMona** [vinceliuice/Orchis-theme#167]
I have noticed that the dropdown menu colors for the ones inside the power/network menu in the top right corner are a white background with black text instead of the opposite. Did I miss anything during the setup (mistyped/unconfigured paremeter) or is this a bug?

Here's a screenshot:
![orchid_issue](https://user-images.githubusercontent.com/31505276/147272457-59371ad8-a640-4596-bae1-3bd3a7fa2ff7.png)

**Comment by MolassesLover** [comment]
Isn't this a stylistic choice made for the Orchis theme? 
![example-1](https://user-images.githubusercontent.com/60114762/147275368-55926877-b393-4367-a6ff-c411cb67939f.png)
![example-2](https://user-images.githubusercontent.com/60114762/147275372-84c33d44-5856-4b0d-81d6-1cb35d65ca8f.png)

**Comment by BonaMona** [comment]
Oh, I thought it was a misconfiguration or something. Thanks for the clarification!
