### ISSUE TITLE
Color of notification-title and mouse-over effect on shell-theme Orchis-grey-light

### ISSUE THREAD

**Issue by doppelhelix** [vinceliuice/Orchis-theme#168]
These are actually two different issues but they occur in the same place.
1. the notification title has a weird color with anti-aliasing enabled. White Sur doesn't suffer from this effect
2. the mouse-over-effect has cut-out corners

build with --shell new for gnome-shell 41.2

The picture shows enabled and disabled anti-aliasing
![notification-antialiasing](https://user-images.githubusercontent.com/4622871/147419242-f93124d2-7091-473a-9d30-338084fdd8d6.jpg)

**Comment by vinceliuice** [comment]
Did you installed any gdm theme?

**Comment by doppelhelix** [comment]
I  did indeed! WhiteSur gdm was installed. Removing it did the trick. 
Thanks.
I find it strange though that the gdm theme is leaking into the desktop. Oh well, gnome-devs hate theming anyway ;)

**Comment by vinceliuice** [comment]
Yes GDM's theme code priority is higher
