### ISSUE TITLE
Files aplication doesn`t have any changes

### ISSUE THREAD

**Issue by CristianArean** [vinceliuice/Orchis-theme#174]
![image](https://user-images.githubusercontent.com/28450215/151663664-af9e6275-ecee-414d-b5ab-805e9814577c.png)
![image](https://user-images.githubusercontent.com/28450215/151663699-3a190a0e-0c82-469c-8305-115a0cabc3b5.png)
As you look, there is no changes in files, but other things in the interface have changed.
Is it a bug or I installed something bad? Thank you for the attention

**Comment by vinceliuice** [comment]
Because you did not change the application theme

**Comment by CristianArean** [comment]
So sorry, i just realizad

**Comment by T-garfield** [comment]
> So sorry, i just realizad

Hi there
Did you fixed it?
I changed mine (even Applications theme) but problem seems remained.

[_Here is link to the issue._](https://github.com/vinceliuice/Orchis-theme/issues/201)
