### ISSUE TITLE
notification history is having time issues

### ISSUE THREAD

**Issue by dtbj** [vinceliuice/Orchis-theme#178]
![demo](https://user-images.githubusercontent.com/87176273/152681095-8d437197-7725-4d55-bc48-1ca887a8441f.gif)
See timings like "just now" that text is messed up.

**Comment by dtbj** [comment]
@vinceliuice Can you please tell me the css class which I can play with?

**Comment by vinceliuice** [comment]
Fixed!

**Comment by dtbj** [comment]
@vinceliuice Please fix in graphite also PLEASE!

**Comment by vinceliuice** [comment]
No problem!

**Comment by dtbj** [comment]
@vinceliuice Thank you so much it means a lot.
