### ISSUE TITLE
Some parts of the UI remain white even when using the dark theme

### ISSUE THREAD

**Issue by Gisbitus** [vinceliuice/Orchis-theme#186]
I'm on PopOS 21.10. I installed the black theme with yellow accents, but the pop ups in my UI remain white, like the control panel or the application search. 
![image](https://user-images.githubusercontent.com/68223680/156880825-df2337b6-a642-4990-b165-779857cf8df3.png)
![image](https://user-images.githubusercontent.com/68223680/156880838-218f83be-a4d9-434f-b67d-c485b17f44f3.png)

**Comment by vinceliuice** [comment]
Yiu need to change the gnome-shell theme
