### ISSUE TITLE
Apps have hardcoded adwaita instead of Orchis

### ISSUE THREAD

**Issue by sheeepdev** [vinceliuice/Orchis-theme#187]
Hey, first I wanna say that I love this theme and use it every day :) Thank you for maintaining it.

I have a few problems, since a lot of gnome apps have recently been switching to GTK4, the themes and icons (the icons that im using are Tela-circle) aren't working, so I have to downgrade to an older version for the apps to be able to work.

Trying to switch the theme with the GTK inspector doesn't work either, it seems they are broken.

~~The only thing im not sure about is if this was fixed in a recent update. My theme is from november so maybe you did some updates in between?~~ Nope. Reinstalled (updated) theme. Still the same.

Here is a example (app is fragments torrent client):

![image](https://user-images.githubusercontent.com/68562536/158055423-8951a3a1-6076-4458-b43c-f566e4c31851.png)

**Comment by GZGavinZhao** [comment]
Fragments is intentional: https://stopthemingmy.app/

**Comment by sheeepdev** [comment]
> Fragments is intentional: [stopthemingmy.app](https://stopthemingmy.app/) Felix Häcker signed his name at the bottom.

So there is no way to theme it?

**Comment by sheeepdev** [comment]
https://github.com/do-not-theme/do-not-theme.github.io/issues/3

This issue may solve some stuff...

**Comment by GZGavinZhao** [comment]
Yes, you cannot theme it, at least not using a theme. I do not think there is anything @vinceliuice can do in this case.

**Comment by MolassesLover** [comment]
I've written a lot of GTK 4 applications and I can confirm Orchis works. I think you should close this issue

**Comment by MolassesLover** [comment]
@sheeepdev It's definitely caused by hard coding Adwaita into the application. GTK 4 vanilla doesn't do that, so the developer went out of their way to force Adwaita. I hope that helps. If you want I can look into the Fragments source code to alter it, but that might take a little while

**Comment by sheeepdev** [comment]
> @sheeepdev It's definitely caused by hardcoding Adwaita into the application. GTK 4 vanilla doesn't do that, so the developer went out of their way to force Adwaita. I hope that helps. If you want I can look into the Fragments source code to alter it, but that might take a little while

That would be amazing if you could do that, because currently I needed to downgrade and miss new features.

**Comment by sheeepdev** [comment]
Anyways, this isnt a problem with Orchis but rather app developers hardcoding adwaita.

**Comment by vinceliuice** [comment]
If gtk4 app use libadwaita then it can not use 3rd themes

**Comment by Thesola10** [comment]
`libadwaita` apps do appear to listen to `$GTK_THEME`, and forcing Orchis onto one causes a few graphical issues, mostly with lists being unthemed and ex-`libhandy` components having incorrect margins.

![image](https://user-images.githubusercontent.com/7287268/162576175-6275500e-9788-4359-823d-94c9897a072a.png)

![image](https://user-images.githubusercontent.com/7287268/162576201-6db34d5b-bcf2-429b-bd49-5f8fa57b7197.png)

**Comment by MolassesLover** [comment]
I'm working on a version of Libadwaita that uses Orchis, rather than Adwaita

**Comment by Thesola10** [comment]
@MolassesLover is this really the right approach? If I understand correctly, that would imply multiplying versions of `libadwaita` for every Gtk theme?

**Comment by MolassesLover** [comment]
It would multiply the versions yeah. I found a better solution, though, which is a lot more streamlined. I'll look into finishing it sometime, but no guarantees, I personally don't use Orchis anymore.

**Comment by MolassesLover** [comment]
Nevermind, Vince beat me to it!

**Comment by Thesola10** [comment]
Well, the new Gtk4 theme (at least on my install on Arch) is systematically dark with a grey accent. Is there a `gsettings` key that needs to be changed?
