### ISSUE TITLE
Gnome 42.0 color issue when hover over elements of shell 

### ISSUE THREAD

**Issue by Smokolak** [vinceliuice/Orchis-theme#189]
**Steps to reproduce:**
**Pre-req:** Orchis theme or Orchis light theme set as shell and applications menu extension installed
1. Click on application menus 
2. Hover over the menus

**Currently:** Black inconsistent backlight appears over hovered elements
**Expected:** Backlight is consistent just like with Gnome ver. 41.x

Current behavior:
![Screenshot from 2022-03-30 09-35-31](https://user-images.githubusercontent.com/9391918/160779074-78de5bf6-700c-4c46-a5a5-4ff13d752e2f.png)

Gnome ver. 41.3
![Screenshot from 2022-03-30 09-49-19](https://user-images.githubusercontent.com/9391918/160779703-4f95c243-aaa1-4c17-9bd0-9112cddec1ba.png)

Test Env: Fedora/Solus distributions, clean installs baremetal&VM

**Comment by F0xxy** [comment]
Same issue in Debian Testing/bookworm
![orchisTheme](https://user-images.githubusercontent.com/10024740/163236811-77a4577a-2b0b-4a5d-870f-deb81d02820b.png)

**Comment by demonkilleralg** [comment]
Same issue here in Arch

**Comment by wrestlerdude** [comment]
Same issue here on Ubuntu 22.04.

**Comment by vinceliuice** [comment]
Fixed!

**Comment by demonkilleralg** [comment]
When can we expect a new stable release?

**Comment by Smokolak** [comment]
Awesome, thanks. Everything works perfect. :)
