### ISSUE TITLE
mount visualize bug

### ISSUE THREAD

**Issue by gaou-piou** [vinceliuice/Orchis-theme#191]
I use reversal icon theme and the mount point look like moved (screenshot: https://ibb.co/2SjzvwZ).

**Comment by MolassesLover** [comment]
This seems like an issue with the Reversal icon theme, not so much Orchis

**Comment by gaou-piou** [comment]
I thought the same thing at first. Until I tried every icon theme I have and it happens exactly the same in all of them

**Comment by vinceliuice** [comment]
This was fixed already, try the last version on github
