### ISSUE TITLE
Pop_OS 22.04 - Theme not applying to file window and other elements

### ISSUE THREAD

**Issue by AMoonRabbit** [vinceliuice/Orchis-theme#196]
Hello,

I recently updated to Pop_OS version 22.04 from 21.10. I believe Gnome has been updated in this version. I re-enabled the user themes extension and re-applied the Orchis Dark red compact theme. However, this only appears to be applying to some elements. The settings window has updated to the theme, however other elements like the file window, and tweaks window do not appear to be applying the theme anymore

![image](https://user-images.githubusercontent.com/3766988/165359494-26bf67d2-e6c4-49c0-8556-25bc1012438b.png)

I am on Gnome 42
Edit: was meant to included something like the below. On the left you can see that the File browser is not themed. But the Settings window on the right is.

![image](https://user-images.githubusercontent.com/3766988/165512032-9f8d6eb8-3783-43c5-9b24-d53345ba4bd7.png)

**Comment by MikeMoolenaar** [comment]
Had the same problem and it only worked for me after switching themes for a few times. 
One way I could 100% get it to work is by having Files open, opening system monitor, searching for `nautilus` and killing the process. It will then show the correct theme upon opening it again.

**Comment by AMoonRabbit** [comment]
Hi Mike, I tried your suggestion but no luck with the theme.

**Comment by Nastas95** [comment]
I have the same problem using Gnome 42 on Arch Linux.

**Comment by MolassesLover** [comment]
Applications that enforce Adwaita break theming support

**Comment by vinceliuice** [comment]
Try this: https://github.com/refi64/stylepak

**Comment by maddoodles** [comment]
> Try this: https://github.com/refi64/stylepak
Not the OP but unfortunately when I tried this the changes revert themselves at seemingly random points. Logging out and logging in again does fit it though.

**Comment by msuleman67h** [comment]
You need to create symbolic link of contents from `~/.themes/Orchis-X/gtk-3.0` `~/.config/gtk-3.0`to

**Comment by maddoodles** [comment]
> You need to create symbolic link of contents from `~/.themes/Orchis-X/gtk-3.0` `~/.config/gtk-3.0`
> 
> Although my wallpaper is now grey. I am not sure how to fix it.

So I tried this and I ended up with a black screen and my cursor when logging in. I had to boot into a demo version of PopOS to fix the folders.

Not sure that quite worked out.

**Comment by msuleman67h** [comment]
> > You need to create symbolic link of contents from `~/.themes/Orchis-X/gtk-3.0` `~/.config/gtk-3.0`
> > Although my wallpaper is now grey. I am not sure how to fix it.
> 
> So I tried this and I ended up with a black screen and my cursor when logging in. I had to boot into a demo version of PopOS to fix the folders.
> 
> Not sure that quite worked out.

What was the symbolic link you created. The "X" was supposed to be placeholder. If your theme is Orchis-red-dark then it would be `~/.themes/Orchis-red-dark/gtk-3.0`

**Comment by cheez20** [comment]
I'm on Pop!_OS 22.04 also and have the same issue, is there any solution to get this to work?

**Comment by johnlevandowski** [comment]
Created pull request https://github.com/vinceliuice/Orchis-theme/pull/218 that may fix this issue when using `./install.sh -c light -l` see issue https://github.com/vinceliuice/Orchis-theme/issues/210

**Comment by AMoonRabbit** [comment]
Latest release of the theme appears to have resolved the issues with selective themeing for me, so I will close this off.

**Comment by AMoonRabbit** [comment]
Latest release of the theme appears to have resolved the issues with selective themeing for me, so I will close this off.
