### ISSUE TITLE
File Manager Theme not applying

### ISSUE THREAD

**Issue by MichaelPetersen22** [vinceliuice/Orchis-theme#197]
I mentioned this error was occuring in Whitesur theme as well. Is the issue perhaps CSS Tag changes for the file manager background? I know extremely little about GTK styling / theming so sadly I am of no assistance in additional problem diagnosing.
![Orchis](https://user-images.githubusercontent.com/72793125/166109587-dec78cdb-9368-41c0-9d32-106dfc1b44e7.png)
![Orchis Dark](https://user-images.githubusercontent.com/72793125/166109590-b2ed1545-85d9-46f7-a58b-ab17f27109a7.png)

Thanks Vince

**Comment by vinceliuice** [comment]
Fixed now!
