### ISSUE TITLE
All Gtk4 variants are dark grey

### ISSUE THREAD

**Issue by Thesola10** [vinceliuice/Orchis-theme#199]
This is a regression introduced somewhere in April, likely in fixing #187, which causes all Gtk4 apps to display a dark variant of the theme with a grey accent colour, regardless of the theme variant used, or whether they use `libadwaita` or not.

Better commit messages would help bisect the issue.

**Comment by Thesola10** [comment]
This is a screenshot of an affected app, Widget Factory, using `Orchis-Yellow-Light-Compact`.
![image](https://user-images.githubusercontent.com/7287268/166235765-2a095fe2-ca21-444f-ab1c-1bee8b2e59c9.png)

This is a screenshot of the Gtk3 widget factory, using the exact same theme.
![image](https://user-images.githubusercontent.com/7287268/166235818-794e8c5a-3337-407e-84dc-745cbcb809b5.png)

**Comment by vinceliuice** [comment]
Gtk 4.0 apps whitch use libadwaita will not support theme follow the tweaks setting, so I just link a dark version of default theme to $HOME/.config/gtk-4.0 to make all gtk 4.0 app use this theme, so if you want to change the gtk 4.0 app theme you need to re-link the theme you want to use by run the install.sh again, for example you want to use: Orchis-Yellow-Light, then you can run `./install.sh -t yellow -c light`

**Comment by Thesola10** [comment]
Given that this behaviour retroactively breaks all Gtk4 apps, may I suggest that this tweak be configurable as a flag in the `./install.sh` script? Something like a `--libadwaita` flag

**Comment by Thesola10** [comment]
Also, your tweak appears to be broken, as when I install `-t yellow -c light -s compact`, the theme that gets linked is `Orchis-Yellow-Compact`, not `Orchis-Yellow-Light-Compact`.

**Comment by vinceliuice** [comment]
About the install.sh issue It's fixed now

**Comment by vinceliuice** [comment]
And I'll add this as a option

**Comment by vinceliuice** [comment]
Fixed!
