### ISSUE TITLE
I set the Shell in Gnome-tweaks to Orchis-Dark-Compact, and get the right top bar and dock. But the Files (or Nautilus) seems didn't change. Can someone help me?

### ISSUE THREAD

**Issue by T-garfield** [vinceliuice/Orchis-theme#201]
_**Issue's image:**_
[Issues&nbsp;Orchis-theme Nautilus](https://i.imgur.com/sbAq4Xg.png)

**Comment by T-garfield** [comment]
Hi. The problem seem remains. Nothing has changed.

**Comment by vinceliuice** [comment]
change the application theme

**Comment by T-garfield** [comment]
Well...

![Screenshot from 2022-05-14 15-51-28](https://user-images.githubusercontent.com/65007264/168426565-af2a92dc-1a9c-48ae-92b2-eedcc8486ea3.png)

**Comment by vinceliuice** [comment]
Why your system can not change application theme？
