### ISSUE TITLE
[GNOME 41] Inconsistency with titlebar buttons. 

### ISSUE THREAD

**Issue by Nakamerica** [vinceliuice/Orchis-theme#203]
Hi @vinceliuice , I've been using this theme for quite a while now, and I've come to notice a slight inconsistency. My System Info: 

![image](https://user-images.githubusercontent.com/88226614/167122469-dc35f028-7f14-4d07-800f-d1430c59dd9b.png)

I've noticed that the titlebar buttons have different pressed shapes in different apps. What i mean by this is that when i press or hover over the buttons, there is one shape in some apps, and another (slightly different) shape in others. I will attach some photos below to illustrate my point. 

The default orchis styled button shape: 

![image](https://user-images.githubusercontent.com/88226614/167123335-84b3e992-e812-4ff0-b0a4-bd68db85e69a.png)

The slightly different shape that is causing the inconsistency (noticed in apps such as spotify, zoom, timeshift, ferdi, etc): 

![image](https://user-images.githubusercontent.com/88226614/167123408-59675b13-9f84-49ef-b148-5fa46c5db403.png)

Perhaps i am wrong, but the second style looks like the graphite-gtk-theme style [which i also use :)]. 

Now, i am wondering how i can make this little inconsistency go away... for some more information, i have also applied the orchis theme to my flatpak apps using Stylepak, so i cannot imagine that my flatpak apps are on a different theme... 

Another bit of information is that when i use any other theme (for example whitesur-gtk) this does not happen. 

Thanks for any help extended.

**Comment by vinceliuice** [comment]
Non-CSD apps will use smaller button style
