### ISSUE TITLE
What color are check boxes?

### ISSUE THREAD

**Issue by madebypixel02** [vinceliuice/Orchis-theme#21]
![Screenshot 2020-07-20 at 2 52 30 AM](https://user-images.githubusercontent.com/40824677/87889903-3a184280-ca34-11ea-8211-57a1c7266607.png)
I see that check boxes are green everywhere, but digging through the different assets I see that the colors are actually blue (just what I wanted). Am I missing something or is green the correct color? If so, is there a simple way to enforce the pixel blue check boxes?

Thank you

**Comment by lfom** [comment]
@vinceliuice The dark variant also have some green widgets. IMO they look out of place... The compact dark variant is great btw, congrats!

**Comment by madebypixel02** [comment]
Going to close this issue, since the last release added options to change the accent color and the default is blue. Thanks for the cool new addition!
