### ISSUE TITLE
Not changing file manager (Nautilus) appearance

### ISSUE THREAD

**Issue by RadioactivePlays** [vinceliuice/Orchis-theme#226]
is this theme supposed to change my file manager appearance? After some work and troubleshooting on Pop!OS it's aparently working in others programs and others parts of the system but my file manager (Nautilus) still untouched.

**Comment by vinceliuice** [comment]
Are you using the last version on github?

**Comment by gortazar** [comment]
Same problem here on an Ubuntu 22.04 (using Xorg). I installed latest Orchis version (master) with:

    ./install.sh -t all -l --shell 42

(also tried with ./install -t all and ./install -t all -l with same results)

I rebooted and everything worked fine.

**Comment by FrancescoSaverioZuppichini** [comment]
same here, not change in nautilus on ubuntu 22.04

**Comment by PhiCecHey** [comment]
Maybe a bit late... but still:
Since Nautilus uses GTK 4, have you applied the Orchis theme so that the GTK 4 apps use it as well and not just the GTK 3 apps? (Or was Nautilus still GTK 3 to the time you asked the question?)
https://github.com/odziom91/libadwaita-theme-changer
The above works for me for all GTK 4 themes and apps.

**Comment by meaz** [comment]
or
```
mkdir -p ~/.config/gtk-4.0
ln -sf /usr/share/themes/Orchis-Dark/gtk-4.0/{assets,gtk.css,gtk-dark.css} ~/.config/gtk-4.0/
```
where you change `Orchis-Dark` by the theme you use

**Comment by meaz** [comment]
Actually, my idea isn't the best. For example if you set Orchis-Green, if you toggle the Dark theme mode button, it stays as Orchis-Green. Would be nice to be able to switch to Orchis-Green-Dark.

**Comment by Demetrio92** [comment]
After installing with a `--libadwaita` flag make sure to set both shell and apps to follow theme in gnome-tweaks:

![Screenshot from 2022-12-17 15-39-33](https://user-images.githubusercontent.com/22682408/208247300-16c338ef-d44a-4ab0-8ab3-83e6119a9624.png)

* make sure to install without `sudo`, so it installs it for your user, not for root. 
* f2 + r for a good measure between each change.

**Comment by wh1t3d3ath** [comment]
Is there any solution to this ? I have the same problem all my apps are on Orchis Dark mode compact , only the fedora manager stays on light mode and it burns my eyes at night

**Comment by vinceliuice** [comment]
@wh1t3d3ath Run `./install.sh -l -c dark`

**Comment by DylanMielot** [comment]
Hi, i had the same issue, i resolved it by replacing all files contained in /.config/gtk-4.0 by those that are in the gtk-4.0 folder of your theme. 
I have to do that each time i change theme

**Comment by dash-09** [comment]
I have followed the above device but this doesnt solve the problem in fedora 41. Even if u apply the theme it doesnt even switch from one theme to another . My nautilus stays on default adwita theme what should I do ???????
