### ISSUE TITLE
Context menu's title is cut

### ISSUE THREAD

**Issue by palexdev** [vinceliuice/Orchis-theme#230]
I don't know why but every context menu on Dash to Panel appears like this:
![Screenshot from 2022-08-08 21-52-05](https://user-images.githubusercontent.com/16880178/183504094-a76591cd-31bf-4496-81e4-b088ac189ef9.png)

Is there a way to fix this?

**Comment by andiemk** [comment]
Hey, I was able to fix this by going to /usr/share/themes/Orchis/gnome-shell/gnome-shell.css and deleting this section:

> .panel-menu .popup-separator-menu-item,
.background-menu .popup-separator-menu-item,
.aggregate-menu .popup-separator-menu-item,
.app-well-menu .popup-separator-menu-item,
.app-menu .popup-separator-menu-item {
height: 6px;
}

This also fixes similar issues I was getting when using ArcMenu with Orchis
