### ISSUE TITLE
LibAdwaita GTK4 theme is broken: Invisible GUI

### ISSUE THREAD

**Issue by Bananaman** [vinceliuice/Orchis-theme#232]
Using theme: `Orchis-Red/gtk-4.0`

It's a beautiful theme and I love it! But these bugs are severe.

Issues:

- The first two issues below can be easily seen in `gnome-text-editor`.

- Bug 1: The filename field of GTK4/LibAdwaita "save" dialogs is totally broken. Black text on black background. Cannot read.

![image](https://user-images.githubusercontent.com/38923130/184435377-c1f74171-7a8a-4ea2-b6fa-d7a4e5a9c0c9.png)

- Bug 2: Recent history/recent files dialog is totally broken. 1: Invisible "open folder" icon. 2: Invisible "X" remove icon. 3: Invisible "full path to file" information.

![image](https://user-images.githubusercontent.com/38923130/184435546-94f3ac86-d3d3-4405-bec8-d3731fd9204b.png)

- Bug 3: The "Disk Usage Analyzer" (baobab) GUI's address bar is broken and unreadable by white text on white background.

![image](https://user-images.githubusercontent.com/38923130/184449764-e0a7388a-d7ef-407e-a0d2-6ff263db9799.png)

**Comment by Bananaman** [comment]
Interesting fact: `Orchis-Light` theme doesn't have this bug?

- Bug 1: On Orchis-light, it's black text on white background, perfect.

- Bug 2: On Orchis-light: All icons and text in that dialog are visible.

So I think and hope that it's an easy fix for the "standard" themes. :)

**Comment by Bananaman** [comment]
Updated to add 3rd bug and clarify that it only affects the Standard theme. :)

**Comment by vinceliuice** [comment]
Fixed now!

**Comment by Bananaman** [comment]
@vinceliuice Thank you so much! I installed the latest version of this theme and confirm that these issues are fixed! <3
