### ISSUE TITLE
Start Menu (Application List Menu) font size too small on high resolution displays 

### ISSUE THREAD

**Issue by wxrl** [vinceliuice/Orchis-theme#234]
See attached on Cinnamon.
This happens on 4K and 3K resolution displays.

![default-font-size-too-small](https://user-images.githubusercontent.com/81678209/184562883-2f15c459-61b1-4de9-b589-165f9c7df737.png)

**Comment by wxrl** [comment]
By changing the `font-size` (originally specified as `9pt`) manually in the `stage` section in `.themes/Orchis-Dark/cinnamon/cinnamon.css` can solve the problem.

Also deleting `font-size: 9pt` in the `stage` section seems letting it use the system font size - not other issues known/seen yet though.

**Comment by vinceliuice** [comment]
Fixed
