### ISSUE TITLE
Gnome 43 Control Panel

### ISSUE THREAD

**Issue by mhkarimi1383** [vinceliuice/Orchis-theme#237]
Hi
I'm using Gnome43 with it's new Control Panel and here is what happened

![Screenshot from 2022-09-02 00-57-40](https://user-images.githubusercontent.com/28821440/188006478-a876da43-5d86-4653-843a-d24e6343329a.png)

**Comment by PhiCecHey** [comment]
I can confirm this. 
Furthermore something similar happens to Nautilus. There are some boxes that should not be there.

I really love your theme and I would be so excited if I could use it again on Gnome 43 :D

**Comment by Drsheppard01** [comment]
I have this issues, but is now resolved with latest release. With much thanks S. Jerusalem

**Comment by vinceliuice** [comment]
Yes, fixed now
