### ISSUE TITLE
power menu still in light mode

### ISSUE THREAD

**Issue by OnlyCS** [vinceliuice/Orchis-theme#238]
![image](https://user-images.githubusercontent.com/61358474/188290268-ac3e21bd-ad0d-47a8-9f6e-c3281a88979e.png)

same with all the other submenus. 

config:
![image](https://user-images.githubusercontent.com/61358474/188290283-cccdd9b5-badd-4aba-9fb2-b4d434c453a6.png)

**Comment by TheAlphaReturns** [comment]
+ all the launcher colors (except the background) is still in light mode (search bar, menu bar)

**Comment by vinceliuice** [comment]
It's just a designed style

**Comment by TheAlphaReturns** [comment]
It's inconsistent

**Comment by Demetrio92** [comment]
duplicates #97

**Comment by Demetrio92** [comment]
@OnlyCS I added a PR with a tweak that fixes it. Please go an test it.

**Comment by OnlyCS** [comment]
Sorry for the late reply. Will test asap.

**Comment by OnlyCS** [comment]
its working for me, it looks a lot more consistent now. Ill close this issue
