### ISSUE TITLE
File managers not looking good

### ISSUE THREAD

**Issue by peter-si** [vinceliuice/Orchis-theme#24]
Hi, I found your theme on https://www.gnome-look.org/p/1357889/ and fall in love with that window design https://cdn.pling.com/img/4/0/4/4/154af2067900edd86e4aee1f25bbdf603dcc.png . However when I installed it, it doesn't look anything like it https://imgur.com/nJeDac0. I'm running i3-gaps-rounded on Arch so maybe I'm missing some non-specified packages?

I tried to install the theme via your installer in git and also tried an AUR package. For file manager I tried it with nemo and nautilus, with the same results. I even tried to install gnome to see if full DE will help, but it didn't. Any idea on how to get the design right?

**Comment by vinceliuice** [comment]
Gnome version must > 3.32

**Comment by alulord** [comment]
I have `local/gnome-desktop 1:3.36.4-1`

**Comment by vinceliuice** [comment]
What's you nautilus version?

**Comment by vinceliuice** [comment]
nautilus also need > 3.32

**Comment by alulord** [comment]
`local/nautilus 3.36.3-1 (gnome)`
`local/nemo 4.6.4-1`

**Comment by vinceliuice** [comment]
![Screenshot from 2020-08-01 17-55-09](https://user-images.githubusercontent.com/7604295/89099209-30bdab80-d420-11ea-8d13-66040de15b8c.png)
I don't know what's going on of your desktop, it should not look like this if you are using the last version of gnome-shell desktop

**Comment by vinceliuice** [comment]
Maybe you can make a new user and try again, if there is some personal settings make this a different

**Comment by cassidymwagner** [comment]
Hi, I'm having the exact same issue as well. Also running arch, i3-gaps-rounded, with gnome and nautilus versions both > 3.32.

**Comment by alulord** [comment]
I found out, that when I install `gnome` and `gnome-extra` and switch to it I have it nice as it should be. So definitely some package missing or we need to start it via gnome (and change WM to i3). But that's not a way I want to go, so even I'm a bit sad, because I love the look I guess I'll try another theme.
