### ISSUE TITLE
Dock padding is a bit too large in ubuntu 22.04

### ISSUE THREAD

**Issue by thepluck** [vinceliuice/Orchis-theme#244]
Hi! Recently I install Orchis-theme in Ubuntu 22.04.01 LTS and have a problem as described in the title.
![image](https://user-images.githubusercontent.com/54402720/194797988-097d3f8d-e2c4-44f0-9fde-b9964094c115.png)
Can I reduce dock padding ? Thanks.

**Comment by vinceliuice** [comment]
./install.sh --tweaks compact

**Comment by thepluck** [comment]
now the problem is solved. Thanks,
