### ISSUE TITLE
how to activate the theme in ubuntu

### ISSUE THREAD

**Issue by quantrpeter** [vinceliuice/Orchis-theme#245]
how to activate the theme in ubuntu? thanks. I have run install.sh but nothing happen

**Comment by vinceliuice** [comment]
Install gnome-tweaks to set theme

**Comment by Drsheppard01** [comment]
gsettings set org.gnome.desktop.wm.preferences theme 'Orchis'
gsettings set org.gnome.desktop.interface gtk-theme 'Orchis'
