### ISSUE TITLE
Nautilus weird fields next to search, since Gnome 43

### ISSUE THREAD

**Issue by PhiCecHey** [vinceliuice/Orchis-theme#246]
I just pulled the repository, so I have the up-to-date version. I removed all previous Orchis themes and installed it like this: ./install.sh -t all -s standard -l
Since Gnome 43 (where they ported Nautilus to GTK 4), Nautilus has these grey fields/bars left and right to the path/search after I apply the theme:

![Screenshot from 2022-10-19 17-38-57](https://user-images.githubusercontent.com/65090580/196739235-372bb536-f7ee-4c12-b95b-543d4c9e9202.png)
![Screenshot from 2022-10-19 17-36-55](https://user-images.githubusercontent.com/65090580/196739275-442e6a59-ca3b-46ba-b35a-b46f3edca587.png)

![Screenshot from 2022-10-19 17-45-09](https://user-images.githubusercontent.com/65090580/196740300-519eb7d9-c788-44ed-b9d5-2dc53e1abd5c.png)

Is this just me or does the theme not support Nautilus GTK 4 yet?

Yesterday's update fixed the shell for me, thank you very much for the update. Besides Nautilus, everything looks as expected. I really love your themes and appreciate all the effort.

**Comment by vinceliuice** [comment]
Download the last update and try again

**Comment by PhiCecHey** [comment]
Thank you for your replay. Before I opened the issue, I pulled the repository; I have the last update from ~2 hours ago. After that I removed all Orchis themes, did sudo killall nautilus (because else sometimes the theme is not applied instantly), installed the theme and applied.

**Comment by PhiCecHey** [comment]
![Screenshot from 2022-10-19 18-06-31](https://user-images.githubusercontent.com/65090580/196745510-9da145e2-766b-47e1-a605-f5f54e5bfb33.png)

**Comment by vinceliuice** [comment]
![截图 2022-10-20 10-13-37](https://user-images.githubusercontent.com/7604295/196840130-ad12f683-52ca-4de3-b099-0c79c3f1746b.png)
![截图 2022-10-20 10-14-06](https://user-images.githubusercontent.com/7604295/196840140-4d92bd14-eb29-46f4-8b6b-6f7b61776473.png)

**Comment by vinceliuice** [comment]
This is my nautilus 43 (gtk4 version) on fedora

**Comment by vinceliuice** [comment]
Check your nautilus version, are you using alpha or beta version?

**Comment by PhiCecHey** [comment]
Since Tumbleweed is rolling release, I thought maybe I have some older files that interfere. I just uninstalled Nautilus and its dependencies and installed it again. Although Zypper installed less packages than uninstalled (which means some dependencies are not needed anymore), that didn't change anything.

**Comment by PhiCecHey** [comment]
Ok I have applied the theme in a fresh Tumbleweed VM. It works just fine there. Sorry for bothering and thank you for your help. I will try to find out what causes my current Tumbleweed to mess with the theme.

**Comment by PhiCecHey** [comment]
I found a lib meta package for nautilus, installed it, applied Orchis theme, it works now. Thank you
