### ISSUE TITLE
( minimize + resize + close  ) icon break

### ISSUE THREAD

**Issue by matty0blake** [vinceliuice/Orchis-theme#247]
There is a problem with the icons that have a dark border like this 

![Screenshot from 2022-10-23 01-08-02](https://user-images.githubusercontent.com/55648361/197364197-d9b2a753-9368-40d9-b440-48c1006b467b.png)

and when i hover it it will show up. which is fine but the black border wont fade away. like this 

![Screenshot from 2022-10-23 01-19-16](https://user-images.githubusercontent.com/55648361/197364346-55a26988-3960-4e55-b44b-dd0adb0c17ec.png)

===========
i think the problem is that the default gtk theme use a grey background and when you hover it it show the icon. and some how the orich gtk-4 cant override it. i couldnt fix it myself as i dont know how gtk work when i tried to fix this and reduce the titlebar height to make the black border become circle and seem like a box that need to hover to show the icon as the default one. 

the default style is like this 

![Screenshot from 2022-10-23 01-18-09](https://user-images.githubusercontent.com/55648361/197364428-24997aa9-1772-4c85-ace8-6db62dedeb16.png)

====
At the End thank you for your works. i love this theme. it give the feeling of modern design

**Comment by vinceliuice** [comment]
What's your system and nautilus version?

**Comment by matty0blake** [comment]
kali-linux-2022.3
DE : Gnome : 43.0
Nautilus : 43.0
gnome-tweaks : 42.beta ( not sure if it affect it. cause it did when i upgraded it to gnome-40 )

**Comment by vinceliuice** [comment]
Did you used plasma desktop before? I did not find this issue on my gnome 43, but what I know is plasma will change gtk app's windows button style to fit it's aurorae theme

**Comment by vinceliuice** [comment]
Try the last update

**Comment by vinceliuice** [comment]
No problem, I'll add this fix
