### ISSUE TITLE
Strange indent

### ISSUE THREAD

**Issue by Drsheppard01** [vinceliuice/Orchis-theme#249]
I don’t understand where this indent for the application menu comes from. It probably conflicts with some setting option.

I use `bash install.sh -c light -t green -l --tweaks compact --round 16px`

- No padding without the compact option (`--tweaks compact`)
- Under unclear circumstances

![Снимок экрана от 2022-10-24 15-46-34](https://user-images.githubusercontent.com/60893791/197529734-802b28f7-8821-4d8d-afa0-ae2a3c490878.png)
![Снимок экрана от 2022-10-21 20-45-38](https://user-images.githubusercontent.com/60893791/197529892-4ce9a9a5-fb0d-4bc4-83f2-4a17fd82b6e8.png)

**Comment by vinceliuice** [comment]
Fixed now!
