### ISSUE TITLE
Bottom corners rounded in all programms like standard gnome apps

### ISSUE THREAD

**Issue by athamour1** [vinceliuice/Orchis-theme#25]
What if all programs bottoms is rounded like the standard gnome apps. For example the file explorer bottom is rounded 
![File Explorer in Pop Os](https://user-images.githubusercontent.com/39333862/89668915-40893400-d8e7-11ea-99d8-611d6143eb6b.png)
but in the Firefox is not 
![Firefox Corner](https://user-images.githubusercontent.com/39333862/89669045-74645980-d8e7-11ea-99ad-6d46b9dfe060.png)
I was googling around but i don't found anything useful. I am sure that it could be done but my gnome-CSS skills is a little bit shitty.

**Comment by vinceliuice** [comment]
Firefox does not support bottom corners

**Comment by athamour1** [comment]
ohhh sorry my bad ;)
