### ISSUE TITLE
Compact theme must be compact

### ISSUE THREAD

**Issue by diegomartarelo** [vinceliuice/Orchis-theme#250]
![Captura de tela de 2022-10-24 15-32-51](https://user-images.githubusercontent.com/6017001/197599658-4d7303ad-6928-4176-940b-9d88a72dfb05.png)

Good afternoon, first of all thank you for the wonderful work! I love and use all your themes! Well, as I mentioned in the main message, I would like the menu bar to be also compact, that is, to be smaller and to take advantage of all the space, notice that there is a border left above and below the menu, mine would be to reduce the space of the menu , make it more compact and thinner, and remove the edges so that it takes better advantage of the screen. What do you think of the idea? :)

**Comment by vinceliuice** [comment]
Trying to fix it. I just don't know what caused this issue.

**Comment by diegomartarelo** [comment]
Yeaahhh! Thanks for the tip! Worked perfectly. :')

**Comment by vinceliuice** [comment]
You are welcome
