### ISSUE TITLE
GTK 4 menu shortcut hint wrong colour and margin

### ISSUE THREAD

**Issue by rekaerst** [vinceliuice/Orchis-theme#252]
In GTK 4 applications, shortcut hints and menu items are next to each other without margin. The colour of shortcut hints is not in grey.

The following warning were shown upon opening a GTK 4 application

```css
(487651): Gtk-WARNING **: 00:09:14.324: Theme parser error: gtk.css:5245:48-49: Expected a valid selector

(487651): Gtk-WARNING **: 00:09:14.324: Theme parser error: gtk.css:5362:21-28: Expected a valid color.

(487651): Gtk-WARNING **: 00:09:14.324: Theme parser error: gtk.css:5447:21-28: Expected a valid color.

(487651): Gtk-WARNING **: 00:09:14.324: Theme parser error: gtk.css:5582:21-28: Expected a valid color.
```
## Reproducing
run `gtk4-demo-application` and `gtk3-demo-application` and compare the appearance of their menus.

GTK 3
![image](https://user-images.githubusercontent.com/52642831/199546110-c4cb186c-1a42-4664-a495-d3be9fcd64d4.png)

GTK 4
![image](https://user-images.githubusercontent.com/52642831/199546174-335dd93c-94a8-4898-8017-1b3db8e2a061.png)

**Comment by vinceliuice** [comment]
Fixed now!

**Comment by rekaerst** [comment]
Thank you!

However, the left padding of `popover.modelbutton.accelerator` is still too small compared to that of GTK 3. Could you please increase it?

**Now:**
![image](https://user-images.githubusercontent.com/52642831/199661294-ee6e678e-16a0-4199-96d8-efe589b977aa.png)
**Increased accelerator padding:**
![image](https://user-images.githubusercontent.com/52642831/199661375-b8d41f6d-b842-4969-97cf-ff51fc36e8cd.png)

**Comment by vinceliuice** [comment]
No problem
