### ISSUE TITLE
High DPI support

### ISSUE THREAD

**Issue by jclsn** [vinceliuice/Orchis-theme#253]
When using high DPI on a 2k or 4k monitor, the borders of the window decorations become too thick. It would be nice if this could be fixed.

![grafik](https://user-images.githubusercontent.com/19779511/200944536-43e9ee81-d94c-49a3-b360-19bba83c472a.png)

**Comment by samex** [comment]
I dont think it will work properly on KDE Plasma, on vanilla Gnome its working perfectly. Should be closed.

**Comment by jclsn** [comment]
Well, if you do it right, it will work on KDE. The Breeze theme does not have this issue. So I think it should be fixed and not just closed, because it works on GNOME.

**Comment by jclsn** [comment]
Oh this is the GTK repo. I did not pay attention to that. Sorry! 

Will make an issue in the KDE repo
