### ISSUE TITLE
White line under tray - MATE desktop

### ISSUE THREAD

**Issue by Neblinus** [vinceliuice/Orchis-theme#260]
I'm using Ubuntu MATE 22.04.1 with Orchis Theme (love it), and there is a strange white line under the system tray. This happens with all the windows (and even without opened windows).
Look at the right upper of the image. If any information needed, just tell me.
![BugTheme](https://user-images.githubusercontent.com/102916102/204163756-f480a0e4-c070-4ddd-8f86-8e3cfa42682c.png)

Discovered that the problem is related to the notification area widget (the tray). If I remove it, the white line dissappears. I will try different things.

**Comment by samex** [comment]
I dont think it will work properly on MATE, on vanilla Gnome its working perfectly. Should be closed.
