### ISSUE TITLE
[Feature Request] A nord colour variant

### ISSUE THREAD

**Issue by ritamsaha00** [vinceliuice/Orchis-theme#261]
I think it needs an option for a Nord color scheme variant

**Comment by ritamsaha00** [comment]
It seems the nord variant is merged, I am closing this issue.

**Comment by vinceliuice** [comment]
OK

**Comment by Demetrio92** [comment]
Indeed, looks my bootleg got merged and then hotfixed. I was in the process of testing it, lol. 

Well, now you can install pretty much the equivalent of the nordic theme using 

`./install.sh --theme teal --color dark --libadwaita --tweaks compact macos primary submenu nord --shell 42`

**Comment by ritamsaha00** [comment]
Btw, @Demetrio92, I want to add some more colorschemes, like Catppuccin or Tokyo Night, can you explain how you added the colorschemes?

**Comment by Demetrio92** [comment]
https://github.com/vinceliuice/Orchis-theme/issues/269 

@ritamsaha00 if anything does not work, ask questions in that thread. I went through the whole codebase and modded it, I probably can help. 

Although you will see that there has been a substantial refactoring effort made and you probably now can simply drop in your color template and it will just work.
