### ISSUE TITLE
  [Feature Request]  whitesur windows buttons

### ISSUE THREAD

**Issue by messi-22** [vinceliuice/Orchis-theme#264]
My favorite theme ever, if you could make an alternative version with the **whitesur windows buttons**,  like Mac, it would be much appreciated!!!

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
Fixed  now you can run `./install.sh --tweaks macos` to get the new style

**Comment by diegomartarelo** [comment]
Great! It is perfect! <3

**Comment by Messii-23** [comment]
@vinceliuice the controls looks kinda white... I mean like the Colloid ones
![Screenshot from 2022-12-08 03-43-12](https://user-images.githubusercontent.com/120075523/206351589-353a4289-602a-4a0f-99e1-426cdbb75a50.png)


I this is what I really mean
![image](https://user-images.githubusercontent.com/120075523/206351834-c3a4f1e9-5d61-4262-a8b4-cb9e80eb283c.png)

**Comment by vinceliuice** [comment]
Change the icon theme, use this one: https://github.com/vinceliuice/Colloid-icon-theme or https://github.com/vinceliuice/WhiteSur-icon-theme
