### ISSUE TITLE
User-defined colors? 

### ISSUE THREAD

**Issue by Demetrio92** [vinceliuice/Orchis-theme#269]
Is there an easy way to edit colors for one of the default variants? I don't mind going through 5 different config files.

**Comment by vinceliuice** [comment]
Edit this file: https://github.com/vinceliuice/Orchis-theme/blob/master/src/_sass/_colors.scss

**Comment by Demetrio92** [comment]
I was able to modify the colors in that file to get some progress on #61 & #261

**Comment by Demetrio92** [comment]
I also noticed that there are some color definitions in 

https://github.com/vinceliuice/Orchis-theme/blob/master/src/gnome-shell/sass/_colors.scss

Are they relevant?

**Comment by Demetrio92** [comment]
Lastly, if I want to get a fully functioning new color variant, how do I re-generate all assets? E.g. this: https://github.com/vinceliuice/Orchis-theme/blob/master/src/gnome-shell/theme-Teal/toggle-on.svg

**Comment by Demetrio92** [comment]
Looks like you went through a full cycle lately: 
https://github.com/vinceliuice/Orchis-theme/commit/a403b82c67c09ef5a0ce97d6fe322974442e669f

@vinceliuice

**Comment by Demetrio92** [comment]
So after digging through the source code of this theme I managed to create a fully fledged bootleg with my custom colored nordic theme. I had to fill in some blanks, here are some useful tips: 

## Contributing

### Color definitions
`src/_sass/_colors.scss`

### Dependencies
`sudo apt install resvg inkscape optipng`

### Rendering / Re-rendering assets
```
bash -c "cd src/gtk && ./render-assets.sh"
bash -c "cd src/gtk-2.0 && ./gtkrc.sh"
bash -c "cd src/gtk-2.0/assets-folder && ./make-assets.sh"
bash -c "cd src/gtk-2.0/assets-folder && ./render-assets.sh"

bash -c "cd src/cinnamon && ./make-assets.sh"
bash -c "cd src/cinnamon && ./render-thumbnail.sh"

bash -c "cd src/gnome-shell && ./make-assets.sh"
```
(some steps are probably forgotten)

### Testing

#### GTK 
`gtk3-widget-factory`
`gtk4-widget-factory`


#### Gnome Shell
`alt+f2` & `rt` -- to reload the shell theme
