### ISSUE TITLE
BUG on dropdown menu

### ISSUE THREAD

**Issue by holiq** [vinceliuice/Orchis-theme#273]
for the result of wifi & power profile like this too, the color still white
ubuntu 22.10
gnome 43
![Screenshot from 2022-12-20 11-03-40](https://user-images.githubusercontent.com/30729921/208581219-d35e598a-d83e-40cb-84be-dea502e4a255.png)

**Comment by karl0st** [comment]
I also have nautilus in light theme

**Comment by Demetrio92** [comment]
duplicates #97

**Comment by Demetrio92** [comment]
@holiq added PR with a tweak that fixes it. Please go an test it.

**Comment by holiq** [comment]
@Demetrio92 awesome mate, I'll test it

**Comment by holiq** [comment]
it's not work on me
[Screencast from 2022-12-24 12-55-01.webm](https://user-images.githubusercontent.com/30729921/209423468-5f36fcb0-69aa-4b8b-b417-8ace64152a1a.webm)

**Comment by Demetrio92** [comment]
Are you sure you even installed my fix? 

```
git clone https://github.com/Demetrio92/Orchis-theme.git
git checkout submenu_style_tweak
./install.sh -c dark -t default -l --tweaks submenu --shell 42
```

Then in the tweaks change the shell theme to something else and back.

**Comment by holiq** [comment]
of course
![Screenshot from 2022-12-31 02-26-39](https://user-images.githubusercontent.com/30729921/210105739-0cbd607e-1be1-4309-81ff-9c56001e269f.png)

**Comment by Demetrio92** [comment]
tested on a vanilla ubuntu 22.04, it still ships with gnome 42, so that works. Looks like a 43 regression. Unfortunately, this is "the gnome way".

**Comment by Demetrio92** [comment]
if you find a theme that works on gnome 43, I could look into porting their code

**Comment by holiq** [comment]
If it's possible then please make it

**Comment by Demetrio92** [comment]
I think it got fixed

**Comment by purpl3-yt** [comment]
> ./install.sh -c dark -t default -l --tweaks submenu --shell 42

thanks it works for me
