### ISSUE TITLE
[Ubuntu 22.10] Compact dark versions don't affect shell menus

### ISSUE THREAD

**Issue by ErikTschierschke** [vinceliuice/Orchis-theme#293]
Ubuntu 22.10 - Gnome Shell 43.1

Compact dark themes don't affect menus of Gnome Shell, while the non-compact versions do.

![image](https://user-images.githubusercontent.com/56506427/214267442-88c08dc5-b416-4746-b32b-ceb2b5e99331.png)
![image](https://user-images.githubusercontent.com/56506427/214267511-b5ed7046-81d6-4fdb-a74d-5c8066d722c4.png)

I'm not an expert with the way Gnome Shell works but as far as I can tell this affects the quick action menu in the top right, the calendar in the middle and the context menu when right-clicking an icon in the task bar.

**Comment by vinceliuice** [comment]
It should be fixed now

**Comment by ErikTschierschke** [comment]
That was pretty fast.
Works perfectly now. Thank you very much
