### ISSUE TITLE
Release 2023-01-25 does not contain prebuilt themes

### ISSUE THREAD

**Issue by alansartorio** [vinceliuice/Orchis-theme#294]
Hi,

I usually find the theme packages under `release` directory in the .tar.gz, but on this release they are missing.

Thanks for this theme!

**Comment by vinceliuice** [comment]
Added https://github.com/vinceliuice/Orchis-theme/releases/tag/2023-01-25

**Comment by 4e554c4c** [comment]
The most recent release ([2023-02-26](https://github.com/vinceliuice/Orchis-theme/releases/tag/2023-02-26)) also appears to not contain packages. This has broken my dotfile scripts.

**Comment by vinceliuice** [comment]
Now add it back
