### ISSUE TITLE
Orange color looks rather peach since nord and dracula was added

### ISSUE THREAD

**Issue by mrmeszaros** [vinceliuice/Orchis-theme#299]
I updated the theme, and noticed that the highlight color of `Orchis-Orange-Dark` has changed from a dark orange to a kind of peach.

![orchis-orange-dark-2023-02-01](https://user-images.githubusercontent.com/15245298/216185517-3ad8e184-c8e7-4b49-b570-e4618fd81d45.png)

I here is the old orange color hue for comparison:

![orchis-orange-dark-old](https://user-images.githubusercontent.com/15245298/216184527-c9dd0851-1f11-47d4-a319-774f131797d6.png)

I did some digging, and the orange hue changed to this peach with the commit 614d5fc _Add nord and dracula colorschemes_.

Was this change intentional, or is the nord color variant accidentally bleeding into the basic dark?

I liked the old one better.

**Comment by vinceliuice** [comment]
Did not notice this, I'll change it back
