### ISSUE TITLE
Shell colors issue 

### ISSUE THREAD

**Issue by RafaelFinance** [vinceliuice/Orchis-theme#300]
I'm not sure if it's a bug or not, which is why I created this case. 

Description
On few dark and black version themes we have white menu. I'm not sure if it shouldn't be dark instead of white as in the dark compact grey or dark compact grey black versions, for example. Screen shot below

Outputs and screens

[rafael@fedora Orchis-theme]$ sudo ./install.sh --tweaks nord submenu compact
Install nord colorscheme ...
Install with themed sub-menus ...
Install compact panel version ...
GNOME Shell 43.0
Installing '/usr/share/themes/Orchis-Nord'...
Installing '/usr/share/themes/Orchis-Compact-Nord'...
Installing '/usr/share/themes/Orchis-Light-Nord'...
Installing '/usr/share/themes/Orchis-Light-Compact-Nord'...
Installing '/usr/share/themes/Orchis-Dark-Nord'...
Installing '/usr/share/themes/Orchis-Dark-Compact-Nord'...

Done.

Resault
![image](https://user-images.githubusercontent.com/125740667/219874516-ac9054fd-b10c-4fd5-8c8e-699de0582a56.png)

[rafael@fedora Orchis-theme]$ sudo ./install.sh --tweaks submenu compact
Install with themed sub-menus ...
Install compact panel version ...
GNOME Shell 43.0
Installing '/usr/share/themes/Orchis'...
Installing '/usr/share/themes/Orchis-Compact'...
Installing '/usr/share/themes/Orchis-Light'...
Installing '/usr/share/themes/Orchis-Light-Compact'...
Installing '/usr/share/themes/Orchis-Dark'...
Installing '/usr/share/themes/Orchis-Dark-Compact'...

Done.

Resault
![image](https://user-images.githubusercontent.com/125740667/219874960-a9e19cf3-2c41-4730-aa8d-0bb6e55fdaab.png)

[rafael@fedora ~]$ sudo ./install.sh --tweaks submenu
[sudo] password for rafael: 
sudo: ./install.sh: command not found
[rafael@fedora ~]$ cd Pobrane/Orchis-theme/
[rafael@fedora Orchis-theme]$ sudo ./install.sh --tweaks submenu
Install with themed sub-menus ...
GNOME Shell 43.0
Installing '/usr/share/themes/Orchis'...
Installing '/usr/share/themes/Orchis-Compact'...
Installing '/usr/share/themes/Orchis-Light'...
Installing '/usr/share/themes/Orchis-Light-Compact'...
Installing '/usr/share/themes/Orchis-Dark'...
Installing '/usr/share/themes/Orchis-Dark-Compact'...

Done.

Resault
![image](https://user-images.githubusercontent.com/125740667/219874960-a9e19cf3-2c41-4730-aa8d-0bb6e55fdaab.png)

Is this the intended effect ?

Fedora 37 Workstation

**Comment by vinceliuice** [comment]
Did you installed Orchis in `/usr/share/themes` and `$HOME/.themes` ?

**Comment by vinceliuice** [comment]
You need run it without sudo

**Comment by RafaelFinance** [comment]
I removed themes from the /usr/share/themes locale then copied the contents of $HOME/.themes to /usr/share/themes and that helped thanks for the hint where issue is. Im closing the issue. 

BTW. In my opinion, most of the projects you have created are very refined and you have a great aesthetic sense. Even if I wanted to, it's hard to get at anything. I can also see that you are developing, the newer project often better refined than the previous one I hope you don't get bored. Thanks for sharing your projects.
