### ISSUE TITLE
All GTK4 apps default to standart Orchis despite other option picked on Gnome 44 beta

### ISSUE THREAD

**Issue by rudi4463** [vinceliuice/Orchis-theme#303]
The issue is as described where i pick anything, like Orchis-Yellow-Dark-Compact, but gtk4 apps just default to Orchis insead.

![Bildschirmfoto vom 2023-02-27 22-18-23](https://user-images.githubusercontent.com/49531544/221688194-765ee379-69eb-4f96-82a9-e5a12be5966d.png)

I installed it with:
`./install.sh -l -t all --tweaks solid compact black primary macos submenu`

I also tried adding --shell 42 and removing all tweaks but the result stays the same.

I also made sure to check if all dependencies are installed.

**Comment by vinceliuice** [comment]
Run `./install.sh -r -l` to remove themes for libadwaita

**Comment by vinceliuice** [comment]
And installed liadwaita theme will cause dark mode can not switch

**Comment by vinceliuice** [comment]
If you want all libadwaita app use dark theme try run: `./install.sh -c dark -l`

**Comment by ForteDexe** [comment]
Thank you, it helps.
