### ISSUE TITLE
No indicator for switched on in quick toggle menu

### ISSUE THREAD

**Issue by youpie** [vinceliuice/Orchis-theme#304]
When using the orchis pink dark theme, the indicator for an option being toggled on is missing. It looks the same as if it was turned off.
![image](https://user-images.githubusercontent.com/37704067/222129062-95943608-baf7-4975-b063-8177a3fe5808.png)  
here you can see it turned off
![image](https://user-images.githubusercontent.com/37704067/222129415-8f3c28b4-9c6d-4fff-b379-ce7c0d2bccef.png) 
this is what it looks like turned on

**Comment by TychoBrouwer** [comment]
I am having the same issue with the vpn selector which does not show the indicator for which vpn is activated

**Comment by TychoBrouwer** [comment]
![image](https://user-images.githubusercontent.com/61564966/234412651-5ccaebae-8ff3-42ed-af70-40a26bbaebfa.png)

This error shows up in journalctl for me when changing the status of the switch to on

**Comment by TychoBrouwer** [comment]
I was using the purple-dark-compact theme, have just checked a bit and the issue is not present for the other purple themes, the light and normal theme. This is the same for the pink theme, the no colour theme however does work.

**Comment by TychoBrouwer** [comment]
I found a solution, commenting this style line in ```gnome-shell/gnome-shell.css``` in the install directory fixes the problem for me

![image](https://user-images.githubusercontent.com/61564966/234428758-23072545-a2b9-4d4f-a71f-21cc08f1c04d.png)

This line is generated from the ```src/gnome-shell/shell-[42 or 44]-0/gnome-shell-Dark.css``` and ```src/gnome-shell/shell-[42 or 44]-0/gnome-shell-Dark-Compact.css```. The line does not seem to be present in the light themed version of this css file.

**Comment by jgdub** [comment]
I can confirm that commenting out this section help but the off indicator is not displaying properly. Look like a dot only and not a slider.

**Comment by jgdub** [comment]
Tested ok on my system. Thank you!
