### ISSUE TITLE
Shell color is grey, not dark

### ISSUE THREAD

**Issue by izzy8799** [vinceliuice/Orchis-theme#306]
My distribution has an old version of the theme that uses dark color or (dark gray) in shell. There is something wrong with this color in the new version. Also, the size of the panel icon is broken, transparency... I don't know how to explain, but you can see the difference in the photos. What should I do?
![old](https://user-images.githubusercontent.com/97313919/222960237-2b068791-171d-42a6-91af-dbc68fd4ce41.jpg)
![new](https://user-images.githubusercontent.com/97313919/222960239-19ef68a5-a515-4eba-af8d-ba3a8c971606.jpg)

**Comment by izzy8799** [comment]
And if anything, I even checked on a real machine, the same problem

**Comment by vinceliuice** [comment]
My fault, did not notice that's changed, I'll make it back!

**Comment by izzy8799** [comment]
> My fault, did not notice that's changed, I'll make it back!

Thanks for the quick response, I'm waiting! When these bugs are fixed, let me know. ❤️

**Comment by vinceliuice** [comment]
You can try it now

**Comment by izzy8799** [comment]
> You can try it now

Thanks, I will try the new version later. I'll let you know how it goes!

**Comment by izzy8799** [comment]
> You can try it now

The problem is partially solved. There is something wrong with the panel and notifications, grayish color. The arc menu icon has shrunk and changed its width. Maybe you should take the sassc or css settings from the 2022 version?

![new](https://user-images.githubusercontent.com/97313919/223167202-5630e54e-82cf-47ea-b2c5-1be3ef9ccc19.png)
![old](https://user-images.githubusercontent.com/97313919/223167210-f0250ab7-7706-4429-b90e-4d7cbfd21db1.png)

**Comment by vinceliuice** [comment]
You can change the icon size in arc-menu menu button settings

**Comment by izzy8799** [comment]
> You can change the icon size in arc-menu menu button settings

What about the color of the panel blur? It doesn't change!

**Comment by vinceliuice** [comment]
What panel blur?

**Comment by izzy8799** [comment]
> What panel blur?

Look at the bottom of the picture. There's a panel there that uses Blur my shell. And in general, the color of the interface is grayer.

**Comment by vinceliuice** [comment]
![Screenshot from 2023-03-08 00-10-43](https://user-images.githubusercontent.com/7604295/223480375-32daaa52-0ba4-4fc6-82e2-a390f1c19886.png)

**Comment by vinceliuice** [comment]
OK, I'll update this

**Comment by izzy8799** [comment]
> OK, I'll update this

Just checked the theme, everything is fine now! Thank you very much for your time ♥️
