### ISSUE TITLE
Nemo location bar has black text on black background

### ISSUE THREAD

**Issue by Riifta** [vinceliuice/Orchis-theme#31]
![nemoissue](https://user-images.githubusercontent.com/9170186/93021108-45e34800-f624-11ea-87ab-c5df4c892a0c.png)

As per the screenshot, the location field in the Nemo file manager appears as black text on a black background with this theme enabled. With other themes, the file manager correctly shows white text on a black background if the theme darkens the location field area.

I'm on Fedora 32 with Gnome 3.36.5. The prerequisites including gtk-murrine-engine are installed.

**Comment by vinceliuice** [comment]
I'll fix this!
