### ISSUE TITLE
[Bug] Nautilus theme don't work well

### ISSUE THREAD

**Issue by windowBR** [vinceliuice/Orchis-theme#313]
It's Just like this
![image](https://user-images.githubusercontent.com/46346833/229299206-a6d5d808-4abd-4a23-8ffe-aec89159cf8c.png)
Ubuntu 22.10

**Comment by Drsheppard01** [comment]
Use -l flag when installing

**Comment by vinceliuice** [comment]
run: `./install.sh -l`

**Comment by windowBR** [comment]
> run: `./install.sh -l`
I trid it but it also have this bug
![image](https://user-images.githubusercontent.com/46346833/229811799-0bc6e02f-3638-4696-aed8-ea0d7130dfc2.png)

**Comment by vinceliuice** [comment]
@windowBR 你要用标准版的话要运行： `./install.sh -c standard -l`  libadwaita 主题没法用tweaks切换  `./install.sh -c dark -l` 就是暗黑版

**Comment by vinceliuice** [comment]
运行完之后要重启nautilus或者桌面

**Comment by windowBR** [comment]
> @windowBR 你要用标准版的话要运行： `./install.sh -c standard -l` libadwaita 主题没法用tweaks切换 `./install.sh -c dark -l` 就是暗黑版

运行了您说的命令并且重启了电脑后依然没有生效，但是又发现了一个奇怪的现象就是当我使用  `$ sudo nautilus` 启动的时候又能正确加载出侧边栏（如图中右侧窗口），但从启动器打开或者从终端 `$ nautilus` 启动的都是左边那种情况
![image](https://user-images.githubusercontent.com/46346833/229822698-fb68a4c9-0fa2-42e3-ac76-04a36c332cd0.png)

**Comment by windowBR** [comment]
> 你安装主题的时候不要加sudo啊， 这样会把主题安装到root用户，所以就会有这种情况

再次尝试后正常了，最开始是因为直接下载了 gnome-look 上面的 tar 包并手动解压到用户目录的 .theme 下后通过 tweak 切换主题出现了这个问题，就让我怀疑是不是权限不够所以后面的操作才用的 sudo，现在看来是自己对主题的使用还是不太了解啊
