### ISSUE TITLE
Unable to use theme after installation

### ISSUE THREAD

**Issue by spartanhooah** [vinceliuice/Orchis-theme#315]
I recently switched my Fedora desktop to MATE. I found your fantastic theme and wanted to try it out. Downloaded the zip, unpacked it, and ran `./install.sh`. The script seemed to go fine, but when I open the Theme tab of Appearance Preferences, the Orchis themes all have strange names that start with an equals sign, e.g. `=Orchis-Compact` and the preview has a large question mark over the image. When I select one of the themes, I get an error message that says "This theme will not look as intended because the required GTK+ theme '=Orchis-Compact' is not installed."

System details:
Fedora 37
MATE 1.26.1

**Comment by samex** [comment]
I dont think it will work properly on MATE, on vanilla Gnome its working perfectly. Should be closed.

**Comment by spartanhooah** [comment]
Same result.
