### ISSUE TITLE
夜间模式部分区域白色

### ISSUE THREAD

**Issue by yuhldr** [vinceliuice/Orchis-theme#316]
- 系统 archlinux
- 桌面 gnome-shell 1:43.4-1
- 主题安装命令 `./install.sh -l -t green -c dark --tweaks macos compact solid --round 5px`

右上角可以展开的都是白色，如图

1|2|3
-|-|-
![image](https://user-images.githubusercontent.com/25719023/231183628-21d6c7c3-a61d-4962-9c87-a362f5f75a33.png) | ![image](https://user-images.githubusercontent.com/25719023/231184186-a6b76c1b-ff47-49a6-8a76-9a3e24b075d2.png) | ![image](https://user-images.githubusercontent.com/25719023/231184282-b5e4d3af-f0a9-471e-8a67-42b1b58637f4.png)

**Comment by yuhldr** [comment]
> 这是独特的设计,模仿的chromeos 的风格 不喜欢的话可以运行：`./install.sh --tweaks submenu` 这样就是普通的菜单啦

原来如此，感谢！

**Comment by vinceliuice** [comment]
不客气
