### ISSUE TITLE
Not matching dark theme in taskbar settings (see picture)

### ISSUE THREAD

**Issue by Neo-29** [vinceliuice/Orchis-theme#320]
![image](https://user-images.githubusercontent.com/90937180/231437366-dc29f4d7-9e89-41c9-8072-21a1bac46c66.png)

Is there a way to correct this?

Tks

**Comment by vinceliuice** [comment]
run ./install.sh -tweaks submenu

**Comment by Neo-29** [comment]
> run ./install.sh -tweaks submenu

Didn't work.
Same result.

**Comment by vinceliuice** [comment]
You should add -t purple for this

**Comment by Neo-29** [comment]
> You should add -t purple for this

I thought it would keep the settings.
So I must do all in one time in the same command?

**Comment by Neo-29** [comment]
> Just run: `./install.sh -t purple --tweaks submenu`

No need for -l variable?

**Comment by vinceliuice** [comment]
You can add, this is the fix for libadwaita app

**Comment by Neo-29** [comment]
> You can add, this is the fix for libadwaita app

Confirmed working after `gnome-shell` restart
