### ISSUE TITLE
Weird alignment of portion/panels and Arrow icons after applying Orchis-Red-Dark theme

### ISSUE THREAD

**Issue by Spectrewolf8** [vinceliuice/Orchis-theme#322]
It's my first time using Orchis-Red-Dark or Orchis theme and I'm facing this weird alignment in my calendar and also the arrows in quick settings that weren't like that when I was using Adwaita or Colloid-Dark theme. I'll leave the screenshots.
My Gnome version is 43.4, and I'm using Arch with Wayland compositor btw.

![image](https://user-images.githubusercontent.com/69973760/232218756-9ec8b8be-2bf6-43d9-a15e-5e316d9b7ca1.png)
![image](https://user-images.githubusercontent.com/69973760/232218826-57b91741-b1eb-4af4-9bb7-8c8323d16de4.png)

**Comment by vinceliuice** [comment]
Download from github and try again

**Comment by Spectrewolf8** [comment]
> Download from github and try again

I did. Firstly I tried downloading it from GitHub and then installing it from the install script. Secondly, I tried downloading it from Pling and then using it.

Both produced the same result.

**Comment by vinceliuice** [comment]
What's you system?
![截图 2023-04-15 23-21-16](https://user-images.githubusercontent.com/7604295/232233854-538441ba-5b26-48e2-a9a0-d9b94a87c6b5.png)
It works all well on my Manjaro

**Comment by vinceliuice** [comment]
What command did you used for install?

**Comment by Spectrewolf8** [comment]
> What's your system? It works all well on my Manjaro ![截图 2023-04-15 23-21-16](https://user-images.githubusercontent.com/7604295/232233897-d4986604-8a70-4daf-a785-82e2371e49a9.png)

I'm using Arch Linux
and I used ```./install.sh -t red```

**Comment by Spectrewolf8** [comment]
@vinceliuice  Hi, I hope you're doing well. I fixed the calendar by adding this to my Gnome-shell.css for the Orchis-Red theme. Should I create a pull request and commit this to your theme :)

![image](https://user-images.githubusercontent.com/69973760/232469632-26b158dc-5ea8-47ee-aa9f-3c08b3636f68.png)

**Comment by vinceliuice** [comment]
![截图 2023-04-18 13-54-22](https://user-images.githubusercontent.com/7604295/232683866-0a8abff5-88af-4aa2-8e46-f792bfd3ac91.png)
It's fixed in the last update

**Comment by Spectrewolf8** [comment]
> ![截图 2023-04-18 13-54-22](https://user-images.githubusercontent.com/7604295/232683866-0a8abff5-88af-4aa2-8e46-f792bfd3ac91.png) It's fixed in the last update

right, please fix or suggest a solution to these misplaced dropdown arrows. 
![image](https://user-images.githubusercontent.com/69973760/232790155-d2839cee-8f87-4972-9110-b577af47da87.png)

**Comment by vinceliuice** [comment]
This theme you are using looks not my theme, I did not find this issue on my desktop

**Comment by Spectrewolf8** [comment]
> This theme you are using looks not my theme, I did not find this issue on my desktop
![image](https://user-images.githubusercontent.com/69973760/232820758-3c2c72f3-5c6e-46f5-bca6-139a9c1da3b1.png)

The theme is yours except for the topbar which I modified according to my preference. It could be the Issue with the Gnome version, which a guy in a subreddit suggested. But it's okay I'll try to fix that on my own. Thankyou for the support.

**Comment by vinceliuice** [comment]
I know the reason now, you are using gnome 43, but you installed gnome-shell 44.0 theme verison for it

**Comment by MMMMMoris** [comment]
> ![截图 2023-04-18 13-54-22](https://user-images.githubusercontent.com/7604295/232683866-0a8abff5-88af-4aa2-8e46-f792bfd3ac91.png) It's fixed in the last update

May I ask about the name of the icon pack?

**Comment by vinceliuice** [comment]
@MMMMMoris  https://github.com/vinceliuice/Tela-circle-icon-theme
