### ISSUE TITLE
Unlicensed GTK app

### ISSUE THREAD

**Issue by konceptosociala** [vinceliuice/Orchis-theme#323]
Please, may I use this beautiful theme for my gtk-rs application, which is licensed under Unlicense license? Or I need to somehow add specific requirements to the project?

**Comment by vinceliuice** [comment]
No problem, You can use it for free

**Comment by konceptosociala** [comment]
> No problem, You can use it for free

Thanks! I am just asking, because GPL license means something like "you can either close it or share it under the same license", but Unlicense makes my application (as well as all included files) a public domain, so it is definitely not the same license
