### ISSUE TITLE
Cinnamon applet toggle issue

### ISSUE THREAD

**Issue by ariasyqolani** [vinceliuice/Orchis-theme#329]
The WiFi applet's on off toggle are invisible when it's off

When it's on
![WiFi on](https://user-images.githubusercontent.com/89631547/234649248-f6b30f52-b4e4-464f-83ec-cfe652979229.png)

When it's off
![WiFi off](https://user-images.githubusercontent.com/89631547/234649263-323d8758-1760-4d98-bf26-9095ae087aab.png)

**Comment by vinceliuice** [comment]
Oh, I'll fix this
