### ISSUE TITLE
Gnome 44 and GKT4 title bars and gnome shell doesn't look like suppose to do

### ISSUE THREAD

**Issue by cchaires** [vinceliuice/Orchis-theme#330]
I run this code to install the theme?
`./install.sh -d /usr/share/themes/  -t green -c dark -s compact -l --tweaks compact --shell 44`

![Screenshot from 2023-04-26 11-08-19](https://user-images.githubusercontent.com/29745531/234679146-59460fce-3ff4-468e-a339-eb1469b40315.png)
Gnome Shell

![Screenshot from 2023-04-26 12-13-55](https://user-images.githubusercontent.com/29745531/234679358-289528d2-7cf8-4231-82f7-d09fd0043d3f.png)
Terminal

![Screenshot from 2023-04-26 12-14-57](https://user-images.githubusercontent.com/29745531/234679563-59310e8e-c9fd-4000-ad7a-b3ae1ebf49f9.png)
Tweaks

Can you help me, why isn't looking like is supposed to look?

**Comment by vinceliuice** [comment]
Run:
```
rm -rf $HOME/.config/gtk-3.0/gtk.css
rm -rf $HOME/.config/gtk-3.0/colors.css
rm -rf $HOME/.config/gtk-4.0/gtk.css
rm -rf $HOME/.config/gtk-4.0/colors.css
```

**Comment by cchaires** [comment]
I have done that, but still the same, I reboot, logout and reinstall the theme but with no success

**Comment by vinceliuice** [comment]
./install.sh -d /usr/share/themes/ ?

**Comment by vinceliuice** [comment]
If you want install in /usr/share/themes/, just run it with sudo
`sudo ./install.sh -d  -t green -c dark -s compact -l --tweaks compact`

**Comment by vinceliuice** [comment]
There is no need install it in both `/usr/share/themes/` and `$HOME/.themes`,

**Comment by vinceliuice** [comment]
Did you changed the css file, because the theme you installed do not looks like standard Orchis theme

**Comment by vinceliuice** [comment]
![截图 2023-04-28 00-36-34](https://user-images.githubusercontent.com/7604295/234930669-8b448ca9-7628-4c43-a3f9-eb6b85f5af04.png)

**Comment by cchaires** [comment]
I did not change anything of the core files.

I delete the folder Orchis from $HOME directory, and give permissions of the folder Orchis theme in usr/share/theme to the users
![Screenshot from 2023-04-27 11-12-19](https://user-images.githubusercontent.com/29745531/234954696-fa30c004-f2ca-4709-a364-d5b776427750.png)

> If you want install in /usr/share/themes/, just run it with sudo `sudo ./install.sh -t green -c dark -s compact -l --tweaks compact`

I tried to run this code, but it says that don't run `sudo` with `-l` option
![Screenshot from 2023-04-27 11-09-50](https://user-images.githubusercontent.com/29745531/234954202-2b66778e-a3e4-42d7-8323-92e8af16b405.png)

You recommend installing the theme in Home directory?

**Comment by vinceliuice** [comment]
If you need -l option then you can only install in ~/.themes without  sudo

**Comment by cchaires** [comment]
I already install the theme from a new Ubuntu 23.04 PC and without errors, all screens shared before look like should.

I will do the same with the old laptop, maybe the error could be that I upgrade from 22.04 to 23.04. Thanks for the help!
