### ISSUE TITLE
ArcMenu button is strange

### ISSUE THREAD

**Issue by izzy8799** [vinceliuice/Orchis-theme#331]
![old2](https://user-images.githubusercontent.com/97313919/235214552-258d7484-e14f-45f5-8aab-a070d30867ee.png)
![new2](https://user-images.githubusercontent.com/97313919/235214606-33b9373b-41a8-49a3-b812-b4c01671521d.png)

Hello again! The new problem is that the ArcMenu button shows up weirdly at all. When clicked, in the old version everything is ok (look in old2.png), but in the new one (look in new2.png), not only there is no dimming animation, but it's also weirdly round. Is this a problem with ArcMenu or the theme? If the theme, please fix it, thank you!

**Comment by vinceliuice** [comment]
What's your gnome version? is this dash to panel?

**Comment by izzy8799** [comment]
1. GNOME 43.4
2. Yes, I use Dash To Panel + ArcMenu

**Comment by vinceliuice** [comment]
Fixed now!

**Comment by izzy8799** [comment]
I'm going to check now, I'll give you an answer in a few minutes

**Comment by izzy8799** [comment]
> Fixed now!

![image](https://user-images.githubusercontent.com/97313919/235336979-eaa59e25-230d-42b3-aae5-2890dd8f7a54.png)
The button is better now, but it's wider and smaller, but I think I can solve that problem here. Thanks for the fix!
