### ISSUE TITLE
Pop-ups and Drop-downs in Firefox Dark theme

### ISSUE THREAD

**Issue by ajowens001** [vinceliuice/Orchis-theme#333]
Hello,

First of all, thank you for all your hard work in creating this theme for the shell/applications/firefox.  Great job.

I did have an issue I would like to bring up and I don't believe it is just limited to the Firefox theme.  After applying the theme according to instruction, I run into the problem where my pop-ups and drop-down buttons or interfaces with selections to choose are way too dark and sometimes invisible.  Please see screenshots for example of what I'm seeing.

https://user-images.githubusercontent.com/48398375/235375495-78ea1dd9-f71f-4463-839e-3bd39dc2122b.mp4

Can you please tell me how to fix this so I can more easily see what I'm selecting in these dialogue windows or website drop-downs, etc.?

![Screenshot from 2023-04-30 13-34-39](https://user-images.githubusercontent.com/48398375/235375128-af9609fb-d899-42b4-b079-b49849481f8b.png)

![image](https://user-images.githubusercontent.com/48398375/235378096-49b115e0-43b2-4b97-9082-450ff9155a43.png)
(The back and forward buttons are invisible; I assure you there are pages I can move between by pressing these invisible button)

Thank you very much!

**Comment by gabrielmmf** [comment]
I also had a similar problem in firefox select boxes. I tried to change the userChrome.css settings but with no success

![image](https://user-images.githubusercontent.com/77760042/235515737-8a9118ae-f48a-4865-be65-f06922a4c974.png)

**Comment by gabrielmmf** [comment]
I managed to solve the problem!! Already made the pull request

**Comment by ajowens001** [comment]
> I managed to solve the problem!! Already made the pull request
Great work!  Will this affect the shell theme with selection options as well as Firefox themed dropdowns?

**Comment by gabrielmmf** [comment]
No, I'm sorry. It affects only the firefox theme...

**Comment by ajowens001** [comment]
> No, I'm sorry. It affects only the firefox theme...
> 
> I changed the pull request name to "Partially fixed"

https://user-images.githubusercontent.com/48398375/235825000-55d2939b-581e-4e8d-9903-6c970204531b.mp4
