### ISSUE TITLE
Orchis theme with Dash to Panel on Fedora 38 with GNOME 44.1 - Intermittent rounded ends visible

### ISSUE THREAD

**Issue by AMoonRabbit** [vinceliuice/Orchis-theme#343]
==Device Information==
OS: Fedora Linux 38 (Workstation Edition) x86_64 
Host: Laptop (12th Gen Intel Core) A4 
Kernel: 6.2.15-300.fc38.x86_64 
Shell: zsh 5.9 
Resolution: 2256x1504 
DE: GNOME 44.1 
WM: Mutter 
WM Theme: Adwaita 
Theme: Orchis-Red-Dark-Compact [GTK2/3] 
Icons: candy-icons-master [GTK2/3] 
Terminal: tilix 
CPU: 12th Gen Intel i5-1240P (16) @ 4.400GHz 
GPU: Intel Alder Lake-P 
Memory: 2588MiB / 15687MiB

==Extensions==
Blur my Shell - Panel settings turned off
User Themes
Dash to Panel
GSConnect
gTile
User Avatar in Quick Settings
AppIndicator and KStatus NotifierItem Support

User Themes is set to Orchis
![image](https://github.com/vinceliuice/Orchis-theme/assets/3766988/019bcb77-d6e4-448b-bd48-fe0566073867)

Gnome Tweaks is also configured to use Orchis
![image](https://github.com/vinceliuice/Orchis-theme/assets/3766988/865dca94-924d-47fb-a771-2ff1b20182cd)

However, despite this, on first load of the DE, i.e. first time firing up the laptop and logging in, the panel bar will not have the rounded edges. You can make them appear by toggling the dash to panel extension/user themes extension off and back on again. 
![image](https://github.com/vinceliuice/Orchis-theme/assets/3766988/0f22e70a-243e-42b5-93dd-2dd609993995)

Edit: Opened an issue on DTP's end too 
https://github.com/home-sweet-gnome/dash-to-panel/issues/1910

**Comment by Bhavyaatrivedi** [comment]
Hi, I think you need to make sure your Fedora Linux installation and all installed packages are up to date.

**Comment by AMoonRabbit** [comment]
I have done `sudo dnf update` and updated packages. Extensions are up to date too.

**Comment by AMoonRabbit** [comment]
Tried removing the theme and then reinstalling with `./install.sh -t red -c dark -s compact -l --tweaks compact --shell 44` but Dash to Panel still does not have the rounded ends. Resizing the length of dtp will also trigger the rounded ends to appear.

**Comment by vinceliuice** [comment]
Change this:
https://github.com/vinceliuice/Orchis-theme/blob/01a359ae6d9f1df79feb71f1fe6c02ee898043fd/src/_sass/gnome-shell/_extensions-40-0.scss#LL264C8-L264C8

**Comment by AMoonRabbit** [comment]
I just ended up overwriting the .themes folder with an older version of the theme after installing with the libadwait theme switch, and so far the dashtopanel rounded edges are staying, and present on fresh boot.
