### ISSUE TITLE
still Same color --> can not read content (gnome session: Orchis-grey-dark) #344 not fix it

### ISSUE THREAD

**Issue by lebakhai** [vinceliuice/Orchis-theme#345]
#344 not fix it 
![image](https://github.com/vinceliuice/Orchis-theme/assets/97871575/303229ca-1e85-4328-94ab-f6b5145942f9)

i reclone git repo (with ```git checkout 9e86fef```)  and reinstall theme but not fix

i think this problem is shell theme beacause i change application theme and it still keep
![image](https://github.com/vinceliuice/Orchis-theme/assets/97871575/00cf8893-77a7-438a-a3bc-88f5f94cc88c)

**Comment by vinceliuice** [comment]
Fixed now
