### ISSUE TITLE
For some apps the top bar is not working properly

### ISSUE THREAD

**Issue by Parthib314** [vinceliuice/Orchis-theme#349]
Like VSCode:
![image](https://github.com/vinceliuice/Orchis-theme/assets/94271200/870c27df-77bd-4c0b-b434-73cf6eb683c3)
I'm using Orchis with macOS and black tweaks. But for some apps (vs code, IntelliJ, Spotify) it doesn't work did I miss anything?
I use `./install.sh --libadawaita --tweaks black macos` to install.

**Comment by vinceliuice** [comment]
Click `alt` + `F2`  then input 'r' to restart gnome-shell on x11, (Relogin your desktop on wayland)

**Comment by Parthib314** [comment]
Ooh, now it works perfectly. Thanks.
