### ISSUE TITLE
Legacy apps inverted titlebars and text

### ISSUE THREAD

**Issue by m05s** [vinceliuice/Orchis-theme#351]
Hi I seem to have a problem with legacy apps, not sure how to solve this, thanks.

With Orchis theme applied + GTK4 styling
![Screenshot from 2023-06-24 00-05-27](https://github.com/vinceliuice/Orchis-theme/assets/76428799/cdb14a5d-7c86-4b5f-adc4-5aaf9738713c)

Without Orchis theme applied + GTK3 styling
![Screenshot from 2023-06-24 01-02-28](https://github.com/vinceliuice/Orchis-theme/assets/76428799/04670d85-8efb-403a-a674-255ff7d88e9c)

**Comment by m05s** [comment]
Ahh I have solved it, sorry to bother everyone 😔😔

**Comment by hugoender** [comment]
What was the solution?
