### ISSUE TITLE
[BUG] Orchis Dark Theme has White Element

### ISSUE THREAD

**Issue by TRENWAR** [vinceliuice/Orchis-theme#353]
![orchis theme issue](https://github.com/vinceliuice/Orchis-theme/assets/69980010/ab696d88-3b21-40f1-a178-50b275bb45d4)

When i use the desktop dark theme of Orchis with the combination of --macos and --dracula, it still somehow has a light theme element.  
It's a small bug and it doesn't discourage me of using this theme but i just wanna report it, hope this issue help the development of this beautiful theme.

**Comment by vinceliuice** [comment]
Run: `./install.sh --tweaks submenu`

**Comment by vinceliuice** [comment]
Now fixed, you can run `./install.sh --tweaks submenu` to install normal menu style
