### ISSUE TITLE
Dash-To-Dock Rendering Issue

### ISSUE THREAD

**Issue by cfn96** [vinceliuice/Orchis-theme#356]
After using ./install.sh in /src/dash-to-dock/
![image](https://github.com/vinceliuice/Orchis-theme/assets/45156056/15740fd6-cf22-4f7d-b9ee-6b2ff5c1dca5)
 Then I tried to uninstall using ./install.sh -r and nothing returns in terminal
 
![image](https://github.com/vinceliuice/Orchis-theme/assets/45156056/218719b7-9745-4352-a084-b162aab31911)

**Comment by vinceliuice** [comment]
Do not run it at last gnome, not support anymore

**Comment by cfn96** [comment]
Thank you for the heads up. I really appreciate your work.
