### ISSUE TITLE
Themes on apps using libadwaita reverts back to the default after update

### ISSUE THREAD

**Issue by Varad-Codes** [vinceliuice/Orchis-theme#368]
I installed the theme using the install script and had the libadwaita flag. After the installation, the apps had the theme but after restart the theme reverts back to the default theme. This only happens with apps using libadwaita

**Comment by vinceliuice** [comment]
Are you using `Material You Color Theming`

**Comment by Varad-Codes** [comment]
yes

**Comment by vinceliuice** [comment]
`Material You Color Theming` or `Custom Accent Colours` are gnome-shell extensions, if you are using one of them you need to turn it off to make sure theme works well

**Comment by Varad-Codes** [comment]
Oh, I was earlier using Custom Accent Colours but removed it after changing the theme
