### ISSUE TITLE
Overlapping in title bars

### ISSUE THREAD

**Issue by sersldmir** [vinceliuice/Orchis-theme#369]
Hi! Running Gnome 44.4 on Linux 6.4.12-arch1-1

When trying to change Displays settings, a weird overlap happens (see the screenshot)

![image](https://github.com/vinceliuice/Orchis-theme/assets/105320309/c28982cf-4a18-435f-b834-611dcf9d0d60)

Can it be fixed?

**Comment by vinceliuice** [comment]
Fixed now

**Comment by sersldmir** [comment]
I uninstalled the the theme using `./install -r`, did `git pull` and installed it with this command `./install.sh -t purple -c dark -l --tweaks primary macos black submenu --round 5px`. After that i rebooted the system. Still overlaps in the exact same place

![image](https://github.com/vinceliuice/Orchis-theme/assets/105320309/d1fb8370-2f03-464e-82ee-4e71f9b58662)

Maybe I need to install it in another way?

**Comment by vinceliuice** [comment]
Now it's ok, I only fixed the headerbar size issue before, but now all fixed

**Comment by sersldmir** [comment]
Yep, the problem disappeared. Thank you very much :)
