### ISSUE TITLE
Activities icon looks bad trimmed after OS update

### ISSUE THREAD

**Issue by ErlanRG** [vinceliuice/Orchis-theme#37]
![image](https://user-images.githubusercontent.com/32745670/97087915-afbf1c00-15ea-11eb-81cc-57226b190022.png)
Hi.
I just upgraded Pop_Os to 20.10 and the icon on the top left bar now looks like if it was badly trimmed on the top and bottom.
Is there a way to fix it and/or change that icon to make it look like before?

**Comment by vinceliuice** [comment]
I'll fix this!

**Comment by ErlanRG** [comment]
Hi. I saw you fixed some items on the repo but not sure if one of those was to fix the icon issue. 
I just reinstalled the themes with the latest changes but the issue still there.

**Comment by 7RST1** [comment]
I'm running the same Pop OS version, but cannot see the issue. Maybe it's fixed now?
