### ISSUE TITLE
Libadwaita theme titlebar issue with standard color

### ISSUE THREAD

**Issue by du207** [vinceliuice/Orchis-theme#374]
I installed by this command:
```bash
./install.sh --tweaks submenu compact -c standard -l
```

There're some issues with titlebar in some libadwaita apps like Settings, Weather, Clock.
It seems the color of texts in titlebar is not correctly assigned in standard color variant.
Gtk 3 apps and nautilus are normal.

Gnome Settings:
![image](https://github.com/vinceliuice/Orchis-theme/assets/140232666/ba1ebff8-e78c-4458-9011-2de53fa7bedb)

Gnome Clock:
![image](https://github.com/vinceliuice/Orchis-theme/assets/140232666/4decac25-d10e-4a9e-8e08-25c2ed3a854f)

OS: Arch linux
Kernel: 6.1.56-1-lts
DE: Gnome 45.0
WM: Mutter
Window System: X11

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by vinceliuice** [comment]
Fixed
