### ISSUE TITLE
libadwaita support fails after rebooting the pc

### ISSUE THREAD

**Issue by thesmartcoder7** [vinceliuice/Orchis-theme#377]
Everything works fine after following the instructions but everything disappears after rebooting the pc. The libadwaita apps just  return to their default look

**Comment by vinceliuice** [comment]
Did you installed some change libadwaita theme color extensions ? that will cause this

**Comment by vinceliuice** [comment]
`Material You Color Theming` and `Custom Accent Colors`

**Comment by thesmartcoder7** [comment]
I had custom accent colors installed but not configured. interesting. Thanks for the help
