### ISSUE TITLE
Switching to List View in File Manager Results in Wrong Theme being Displayed (GNOME 45.0)

### ISSUE THREAD

**Issue by masterdokuro** [vinceliuice/Orchis-theme#378]
I've upgraded to ubuntu 23.10 with GNOME 45.0 and I'm using the default theme and colour.  Here is the command I use to install them.

./install.sh --theme default --color standard --libadwaita
./install.sh --tweaks submenu

However, within File Manager when I switch to using the list view from the grid view the theme changes to the dark theme.

From:
![Screenshot from 2023-10-18 09-41-37](https://github.com/vinceliuice/Orchis-theme/assets/148326796/725d013b-ea10-4c41-a74b-479e6df81b65)

to:
![Screenshot from 2023-10-18 09-42-00](https://github.com/vinceliuice/Orchis-theme/assets/148326796/c4a1e102-7138-4899-bd24-98241a54e9fc)

This does not happen with the previous version of GNOME 44.0.

**Comment by vinceliuice** [comment]
Fixed
