### ISSUE TITLE
dark theme inconsistency

### ISSUE THREAD

**Issue by FilthySchmitz** [vinceliuice/Orchis-theme#379]
Hi! in the dropdown selection for the options in the power menu the background is white, I'm on gnome 45, if you need more details let me know

![image](https://github.com/vinceliuice/Orchis-theme/assets/130904480/45a8403e-1eb3-45a0-a77d-41d223b8fd20)

![image](https://github.com/vinceliuice/Orchis-theme/assets/130904480/301e2459-e054-402f-a5bb-41000f3277db)

**Comment by vinceliuice** [comment]
`./install.sh --tweaks submenu`

**Comment by FilthySchmitz** [comment]
solved, thank you very much!

**Comment by vinceliuice** [comment]
You are welcome!
