### ISSUE TITLE
Highlight issue with text editor on current line

### ISSUE THREAD

**Issue by xpt1x** [vinceliuice/Orchis-theme#38]
Current line highlights with white color on orchis-dark which makes text on line unreadable
Using latest version from Github

![gnome-shell-screenshot-DSIVS0](https://user-images.githubusercontent.com/33655587/97138770-f3e32580-177e-11eb-8dc8-1828748e7a5d.png)

**Comment by vinceliuice** [comment]
Not theme issue, change the default color scheme of gedit can fix this
