### ISSUE TITLE
Thin White Line on the top of the File Manager window (GNOME 45.0)

### ISSUE THREAD

**Issue by masterdokuro** [vinceliuice/Orchis-theme#380]
I've upgraded to ubuntu 23.10 with GNOME 45.0 and I've noticed a thin white line on the top of the File Manager window (see screenshot below).  Below are the commands I use to install the theme.

./install.sh --theme default --color standard --libadwaita
./install.sh --tweaks submenu compact --shell 44

![Screenshot from 2023-10-28 09-21-12](https://github.com/vinceliuice/Orchis-theme/assets/148326796/a1666f5a-039e-478c-9df3-7a0b8e0f88b2)

This can be a little hard to see if you don't have a dark background wallpaper behind the File Manager window.  Other applications don't show this.  Also, this did not happen with the previous version of ubuntu and its gnome version.

**Comment by vinceliuice** [comment]
Fixed

**Comment by masterdokuro** [comment]
Brilliant, thank you.  While this looks minor it was really annoying me :-)
