### ISSUE TITLE
Hovering bug

### ISSUE THREAD

**Issue by sersldmir** [vinceliuice/Orchis-theme#381]
Hi there!

The system is Arch (Linux 6.5.8-arch1-1 on Wayland) and the app is Remmina. Gnome 45

There is a bug with hovering in the options submenu (see the screenshot)

It works fine with the default theme so maybe it has smth to do with the theme (used installation command: `./install.sh -t purple -c dark -l --tweaks primary macos black submenu compact solid`)

Can it be fixed or is the app causing the issue?

![image](https://github.com/vinceliuice/Orchis-theme/assets/105320309/4d051eed-74b6-42a4-981c-d36f340f85c5)

**Comment by vinceliuice** [comment]
Fixed

**Comment by sersldmir** [comment]
Thanks a lot
