### ISSUE TITLE
GNOME Settings Left Panel Color Issues (GNOME 45.0)

### ISSUE THREAD

**Issue by masterdokuro** [vinceliuice/Orchis-theme#383]
I've noticed with a recent update to the orchis theme that the GNOME Settings panel has suffered a regression on the left panel.  The themes are installed using the following...

./install.sh --theme default --color standard --libadwaita
./install.sh --tweaks submenu compact --shell 44

... and the panel now looks like this
![Screenshot from 2023-10-29 15-56-07](https://github.com/vinceliuice/Orchis-theme/assets/148326796/a24d386d-5096-4623-87fe-784cc3b6992f)

I've only observed this happening after I updated the theme to fix https://github.com/vinceliuice/Orchis-theme/issues/380 but I guess https://github.com/vinceliuice/Orchis-theme/issues/381 may also have effected it.

**Comment by vinceliuice** [comment]
What's your desktop version ?

**Comment by masterdokuro** [comment]
I'm sorry, I should have said that in my report.  Its ubuntu 23.10.

**Comment by vinceliuice** [comment]
Fixed now

**Comment by masterdokuro** [comment]
Thank you, confirmed fixed.  Much appreciated.
