### ISSUE TITLE
Broken quick settings panel (gnome 45)

### ISSUE THREAD

**Issue by FelixFourcolor** [vinceliuice/Orchis-theme#389]
Everything is dark, except the submenus are light.

![Screenshot from 2023-11-10 16-05-54](https://github.com/vinceliuice/Orchis-theme/assets/34260584/a8a676e8-9861-4e09-b5a3-e504a9e7653e)

Thank you for the beautiful theme, by the way. I've been using your WhiteSur theme, and only recently discovered this one. I'll probably switch.

**Comment by vinceliuice** [comment]
`./install.sh --tweaks submenu`

**Comment by FelixFourcolor** [comment]
@vinceliuice Thank you so much!
