### ISSUE TITLE
incorrectly coloured 'file operations' panel in the file explorer

### ISSUE THREAD

**Issue by jadenous** [vinceliuice/Orchis-theme#403]
![Screenshot from 2024-02-02 18-14-52](https://github.com/vinceliuice/Orchis-theme/assets/125571598/70078f50-bdc6-4a3c-a70a-a4860b4f8399)

fedora 39, gnome 45, on a virtual machine, installed with the following command:
`/install.sh -c standard -t default --tweaks solid black compact -l`

**Comment by vinceliuice** [comment]
Fixed
