### ISSUE TITLE
Inconsistent Dark Theme Compact

### ISSUE THREAD

**Issue by norigeist** [vinceliuice/Orchis-theme#41]
Every panel in the top bar is showing the system light theme with the *Orchis dark compact* theme.

![orchis-dark-compact](https://user-images.githubusercontent.com/74561250/99290392-863a8e80-283e-11eb-9979-01c0958bd66c.jpg)

For reference the *Orchis dark* (standard size) theme is displaying the dark theme, as it should for compact as well.

![orchis-dark](https://user-images.githubusercontent.com/74561250/99290390-85a1f800-283e-11eb-913a-b4bace2004ed.jpg)

---
OS: Pop!_OS 20.10
Release: 20.10
Codename: groovy
Gnome Version: 3.38.1

**Comment by lfom** [comment]
I guess you need to install User Themes extension, and then apply the same them for the Shell.

**Comment by norigeist** [comment]
> I guess you need to install User Themes extension, and then apply the same theme for the Shell.

Ah yes. Thank you for the hint. 
However that would also change the appearance of the top bar as well, which I don't want. It is still strange that the *default* dark displays the dark theme whereas the *compact* does not.

**Comment by lfom** [comment]
> > I guess you need to install User Themes extension, and then apply the same theme for the Shell.
> 
> Ah yes. Thank you for the hint.
> However that would also change the appearance of the top bar as well, which I don't want. It is still strange that the _default_ dark displays the dark theme whereas the _compact_ does not.

Now that you have User Themes extension, use Pop-dark, and you will have the look you want.
