### ISSUE TITLE
Weird colors in Dash (Gnome 46)

### ISSUE THREAD

**Issue by TiagodePAlves** [vinceliuice/Orchis-theme#410]
Arch Linux just updated to Gnome 46, and now I'm seeing weird colors for the Dash.

Here is how the Dash looks with `Orchis-Dark-Compact` set as the shell theme:

![orchis-enabled](https://github.com/vinceliuice/Orchis-theme/assets/22567908/9dcaface-d4b0-435a-ae78-2142eba6f09f)

Here is the same view with the default theme:

![default-theme](https://github.com/vinceliuice/Orchis-theme/assets/22567908/efcab9be-fd2d-40e7-9052-0cec57dc2f31)

I'm not sure if this is working as expected or if this has already been fixed in main.

## Additional Details

- Shell version: GNOME Shell 46.0 (arch: [gnome-shell 1:46.0-1](https://archlinux.org/packages/extra/x86_64/gnome-shell/))
- Orchis version: 2023_10_20 (AUR: [orchis-theme 2023_10_20-1](https://aur.archlinux.org/packages/orchis-theme))
- Windowing System: X11

**Comment by Anto426** [comment]
same problem

**Comment by jgdub** [comment]
I can confirm this too.

Arch, Wayland, Gnome 46

**Comment by bubner** [comment]
+1

**Comment by Sr-0w** [comment]
Same for me in Arch with gnome 46 on x11
