### ISSUE TITLE
blocky cointainers around icons and dock is square. some elements look buggy (GNOME 46)

### ISSUE THREAD

**Issue by DowneyX** [vinceliuice/Orchis-theme#411]
### problem
buggy elements
![image](https://github.com/vinceliuice/Orchis-theme/assets/57352505/1b1721bf-0314-4f8f-a8e5-1cc4d876a784)

odd looking dock.
![image](https://github.com/vinceliuice/Orchis-theme/assets/57352505/69efe7d7-957e-4d7f-a969-bd4c5038bc30)

i recently enabled Wayland on my device and ever since then it's been like this.
even if i go back to x11 the issue persists.

### What i have tried
I've tried reinstalling the theme but to no avail. 

### additional details
- Shell version: GNOME Shell 46.0
- OS: Arch Linux x86_64
- WM Theme: Orchis-Dark
- Theme: Orchis-Dark [GTK2/3]
- Icons: Tela [GTK2/3]

**Comment by bubner** [comment]
+1, seems to be bugs emerging after upgrading to GNOME 46

**Comment by luis-cvqz** [comment]
+1, This happened to me after upgrading to 46. I don't know what distro are you using, but for me on arch linux a temporary fix was to downgrade the gtk3 and gtk4 packages and that fixed the blocky containers. Again, I don't know what distro are you using, but that might help in the meantime.

**Comment by stel-bl** [comment]
> +1, This happened to me after upgrading to 46. I don't know what distro are you using, but for me on arch linux a temporary fix was to downgrade the gtk3 and gtk4 packages and that fixed the blocky containers. Again, I don't know what distro are you using, but that might help in the meantime.

@luis-cvqz mind telling what versions did you downgrade those packages to? It would be pretty good for future reference.

**Comment by luis-cvqz** [comment]
> > +1, This happened to me after upgrading to 46. I don't know what distro are you using, but for me on arch linux a temporary fix was to downgrade the gtk3 and gtk4 packages and that fixed the blocky containers. Again, I don't know what distro are you using, but that might help in the meantime.
> 
> @luis-cvqz mind telling what versions you downgraded those packages to? It would be pretty good for future reference.

@stel-bl I downgraded gtk3 to gtk3-1:3.24.40-2, and gtk4 to gtk4-1:4.12.5-1

**Comment by stel-bl** [comment]
> > > +1, This happened to me after upgrading to 46. I don't know what distro are you using, but for me on arch linux a temporary fix was to downgrade the gtk3 and gtk4 packages and that fixed the blocky containers. Again, I don't know what distro are you using, but that might help in the meantime.
> > 
> > 
> > @luis-cvqz mind telling what versions you downgraded those packages to? It would be pretty good for future reference.
> 
> @stel-bl I downgraded gtk3 to gtk3-1:3.24.40-2, and gtk4 to gtk4-1:4.12.5-1

Alrighty thanks! I'll try as well.
