### ISSUE TITLE
On Orchis-Light when highlighting item on desktop makes the icon black

### ISSUE THREAD

**Issue by sudcapitano** [vinceliuice/Orchis-theme#416]
![immagine](https://github.com/vinceliuice/Orchis-theme/assets/155137455/5b7fe4d5-9f94-47b6-a9ec-852972a87650)
As you can see it is pretty weird, but on the Orchis-Dark it looks fine.

**Comment by vinceliuice** [comment]
What dekstop you are using ?

**Comment by sudcapitano** [comment]
I'm using XFCE on Arch

**Comment by vinceliuice** [comment]
Fixed
