### ISSUE TITLE
Window action buttons broken on Firefox 125 (Debian 12.5 & Fedora 40)

### ISSUE THREAD

**Issue by JVintimilla** [vinceliuice/Orchis-theme#418]
![Screenshot from 2024-04-25 19-19-17](https://github.com/vinceliuice/Orchis-theme/assets/90857245/e2511029-38bc-4dff-9645-05660d126718)

As you can see in the picture the window action icons are spaced to close together, and are to close to the edge of the window. This happens when the window is maximized or when is not.

I'd like to point that I used the latest version of the theme (As of today, April 25th) before editing this issue. I'd also like to point out the command I used to install the theme in my system: `./install.sh -t purple --tweaks macos --tweaks compact --tweaks primary --round 8px`

**Comment by JVintimilla** [comment]
Today, April 25th I tried the latest release of Fedora Workstation 40, with the GNOME desktop, and the issue that was originally reported persists. I'm assuming this is a Firefox change, however I could also see this while using the Jasper theme. @vinceliuice

**Comment by Abragus** [comment]
Having the same issue with Fedora 39/Gnome 45, I believe since the Fedora update that brought kernel 6.8.6 (not that the kernel itself is a likely culprit, but something that was shipped at the same time probably is.)

**Comment by JVintimilla** [comment]
Tried Firefox 126, the reported issue keeps happening

**Comment by JVintimilla** [comment]
Reported issue seems to be improved with Firefox 127. It appears it has nothing to do with the theme. Therefore, I'll close this issue.

**Comment by padgriffin** [comment]
I'm a year late to this but this can be fixed by adding  this snippet into `userchrome.css`. Adjust the pixel values to your liking- this is just how I have mine set up.

`.titlebar-buttonbox-container {margin-left: 16px !important;}`

`.titlebar-button {padding: 1px 7px !important;}`
