### ISSUE TITLE
Search Everywhere within Nautilus results in wrong theme being displayed (GNOME 46.0)

### ISSUE THREAD

**Issue by masterdokuro** [vinceliuice/Orchis-theme#423]
I've upgraded to fedora 40 with GNOME 46 and I'm using the default theme and colour. Here is the command I use to install them.

./install.sh --dest ~/.local/share/themes --theme default --color standard --size compact --libadwaita --tweaks submenu --round 9

However, within Nautilus when I switch to using the Search everywhere the theme changes to the dark theme.

From:
![Screenshot from 2024-04-24 18-37-26](https://github.com/vinceliuice/Orchis-theme/assets/148326796/caad2cf7-d474-4f6a-9dfa-e132ee9f6e00)

To:
![Screenshot from 2024-04-24 18-37-38](https://github.com/vinceliuice/Orchis-theme/assets/148326796/a476c92e-ebde-4150-9610-ef39ebe74fd5)

The **Search Everywhere** is opened by selecting the search icon on the top left Nautilus.

**Comment by masterdokuro** [comment]
BTW... having multiple tap open looks like this ...

![Screenshot from 2024-04-24 18-45-45](https://github.com/vinceliuice/Orchis-theme/assets/148326796/f7148627-2ac5-4113-a569-7d9fe55f1134)

**Comment by vinceliuice** [comment]
Fixed
