### ISSUE TITLE
Bug: Notifications displayed across entire screen and removed from clock menu

### ISSUE THREAD

**Issue by cdoenges** [vinceliuice/Orchis-theme#427]
On Gnome 43.9 (X11, Debian 12) after installing v2024.04.18 notifications are displayed across the entire width of the screen with the text only in a very slim box. They are also not added to the clock menu.

Example:
![flameshot-notification](https://github.com/vinceliuice/Orchis-theme/assets/1794439/3367e0d0-1839-4b69-ba7b-08d6ddf6d3a5)

Reverting to an old theme version (around September 2022) or to the default Gnome shell theme restores the old behavior.

**Comment by vinceliuice** [comment]
How did you install the theme ? by the way release files are made for gnome-shell 46 version

**Comment by killi1812** [comment]
I have the same issue and I installed the theme over https://www.gnome-look.org/p/1357889/

**Comment by vinceliuice** [comment]
@killi1812  Download this theme from github and run `./install.sh` to install it, theme files on gnome-look only works for gnome-shell 46 version

**Comment by BBFifield** [comment]
Same issue on my system with a fully updated Gnome 46 and the latest pull from master branch.

**Comment by CodeAndGin** [comment]
Same issue here too, up to date Gnome (on arch), most recent pull.

**Comment by vinceliuice** [comment]
What about now ?

**Comment by damien-carcel** [comment]
Hello @vinceliuice.

The shell theme from the master branch is now working for me. I installed as follow:
```bash
./install.sh -t orange -c standard -l --shell 46
```
With the latest stable release, I would have use `--shell 44`, which didn't work.

The strange thing is I have 2 laptops, both running an up-to-date Arch Linux, with the same software installed on it (I compared the package lists): one has the issue, the other not :thinking:.

Anyway, thank you for your hard work and this beautiful theme!

**Comment by CodeAndGin** [comment]
Most recent pull didn't do much, but the commit diffs gave me an idea of where to look. Adding border: 1px to .notification-banner (round about line 1960 of gnome-shell.css after running ./install) fixed it for me (Don't ask me why, CSS is inscrutable magic to me)

**Comment by BBFifield** [comment]
> Hello @vinceliuice.
> 
> The shell theme from the master branch is now working for me. I installed as follow:
> 
> ```shell
> ./install.sh -t orange -c standard -l --shell 46
> ```
> 
> With the latest stable release, I would have use `--shell 44`, which didn't work.
> 
> The strange thing is I have 2 laptops, both running an up-to-date Arch Linux, with the same software installed on it (I compared the package lists): one has the issue, the other not 🤔.
> 
> Anyway, thank you for your hard work and this beautiful theme!

Yeah, running with the `--shell 46` option or without works for me. 

The Github instructions states `44                 Gnome-shell version >= 44.0`, which led me to believe that I had to use `--shell 44` for any shell version 44 and above.

`./install -h` does show the correct available options.

Might be a good idea to update the README so this pop up again in the future. 

Thank you @vinceliuice for your diligence and dedication in continuing to update this theme. Yours efforts don't go unnoticed!
