### ISSUE TITLE
Please exclude unnecessary css files from git

### ISSUE THREAD

**Issue by kevinhwang91** [vinceliuice/Orchis-theme#433]
Thanks for your hard work in maintaining this repo. I want to customize the theme based on `Orchis` for mine, but I don't want to lose any new fixes/updates in this repo. 

For now, I must merge the `master` branch into my branch, but the `css` files produced by `parse-sass.sh`  in `master` are always conflicted with my branch, which makes too many unnecessary merge processes for hacking.

**Comment by vinceliuice** [comment]
Now it's ok

**Comment by kevinhwang91** [comment]
> Now it's ok

Thanks! Now I can fork the repo and add my GitHub action to merge the future conflicted commit easily.
