### ISSUE TITLE
KiCad dark mode is broken

### ISSUE THREAD

**Issue by Calvicii** [vinceliuice/Orchis-theme#441]
KiCad is broken when using Orchis as a theme. The dark mode works fine with the base Linux Mint styles.
![Screenshot from 2024-05-28 02-47-49](https://github.com/vinceliuice/Orchis-theme/assets/80085756/67a3f7de-f423-4742-aef8-8b9e4ad00128)

**Comment by vinceliuice** [comment]
Fixed now

**Comment by maederan201** [comment]
I still seem to have this issue with kicad 9.0.7. Although the toolbars are shown correctly, the inner UI of kicad is not. With breeze it works as it is supposed to...
