### ISSUE TITLE
Gnome 46.1 broken lock-screen

### ISSUE THREAD

**Issue by SeineEloquenz** [vinceliuice/Orchis-theme#442]
When using the theme on Gnome 46.1, my lockscreen is broken.
The profile picture is collapsed into a one pixel wide column and the input field is invisible.
See the following screenshot:
![Screenshot from 2024-05-28 17-07-14](https://github.com/vinceliuice/Orchis-theme/assets/34923333/1726297e-cf87-4312-a6c0-7149828c2518)

**Comment by vinceliuice** [comment]
Lock screen using default GDM (gnome-shell) theme, do not use 3rd themes, how could this happen ?

**Comment by SeineEloquenz** [comment]
I have only installed orchis theme, nothing else. I sadly don't know why this happens.
Something I can do to help debug this?

**Comment by SeineEloquenz** [comment]
This was not obvious to me, but it is a problem with the font I installed for GTK, not orchis itself.
Closing this.
