### ISSUE TITLE
Text Event Color in Calendar App same as Background Calendar Color

### ISSUE THREAD

**Issue by rizaldimaulidia** [vinceliuice/Orchis-theme#444]
Hi, I love your theme. I use Orchis Orange Dark Theme in Ubuntu 22.04. But I have an issue with my Calendar, The event text on the calendar is the same color as the background color of the calendar, so the event text cannot be read.

I have attached a screenshot. Please fix this issue, thank you.

![Screenshot from 2024-06-12 08-06-06](https://github.com/vinceliuice/Orchis-theme/assets/8392772/0f9bdb0d-487d-42fa-bf66-196ea15e432e)

**Comment by vinceliuice** [comment]
This theme in your picture is not Orchis
