### ISSUE TITLE
GTK Colors not applying

### ISSUE THREAD

**Issue by abb3v** [vinceliuice/Orchis-theme#449]
No matter what color for the theme I use, regardless of using libadawati flags, I still cannot get GTK to work properly:
![Screenshot from 2024-06-25 13-02-05](https://github.com/vinceliuice/Orchis-theme/assets/166838215/9c685985-2951-4e28-96a1-cf70f07d9b00)

I have it set to use Dark Theme yet its still showing up as light everywhere?

**Comment by vinceliuice** [comment]
Gtk4.0 apps are not Legacy Applications, so you can not change it from Tweaks

**Comment by vinceliuice** [comment]
Run: `./install.sh -c dark -l` to get the dark look for gtk4.0 (libadwaita) apps

**Comment by abb3v** [comment]
I apologize. I failed to read the documentation on this one
