### ISSUE TITLE
Shell notification bubble taking up the entire width of the screen

### ISSUE THREAD

**Issue by dchristofolli** [vinceliuice/Orchis-theme#459]
Shell notification bubble taking up the entire width of the screen when using orchis as shell theme. The message is not displayed correctly either. I'm using debian 12 stable with gnome-shell 43.9
![image](https://github.com/user-attachments/assets/a471285e-5a6e-4399-99f6-6cdb640597a9)

**Comment by vinceliuice** [comment]
Downloda from github and run: `./install.sh`

**Comment by dchristofolli** [comment]
This way worked to me. Thank you!

**Comment by vinceliuice** [comment]
You are welcome!
