### ISSUE TITLE
Ubuntu Software Store and Synaptic not in dark theme with Orchis Dark or Dark compact

### ISSUE THREAD

**Issue by meesterexx** [vinceliuice/Orchis-theme#47]
Ubuntu 20.10 x64, with either Orchis-dark or Orchis-dark-compact set for applications and shell, the Ubuntu Software Store and Synaptics Package Manager are showing up in light theme. They do show up in dark mode when Applications theme is set to either either Adwaita-dark or Yaru-dark so it seems specific to the Orchis dark Applications themes.

![Screenshot from 2020-12-18 16-44-42](https://user-images.githubusercontent.com/13154733/102664283-6bff1380-4150-11eb-8817-f33c460d0050.png)

![Screenshot from 2020-12-18 16-45-45](https://user-images.githubusercontent.com/13154733/102664352-8df89600-4150-11eb-94b2-d3b2fd74fd02.png)

**Comment by vinceliuice** [comment]
Install this theme with sudo

**Comment by meesterexx** [comment]
Thank you for the quick reply. Installed with sudo and Synaptics is fixed, but Ubuntu Software store is still in light theme. I tried rebooting and setting to Yaru-dark and back to Orchis -dark.
