### ISSUE TITLE
xfce4 panel text disappears in non-dark variants (quick and dirty fix included)

### ISSUE THREAD

**Issue by leoctrl** [vinceliuice/Orchis-theme#48]
I like this theme a lot, but when I select any non-dark version, the text in my xfce4 panel disappears. (I'm using xfce4-panel 4.14.1 and gtk 3.24.5)
Attached is my quick and dirty workaround [xfce4_panel_fixes_for_non_dark_themes.patch.txt](https://github.com/vinceliuice/Orchis-theme/files/5719435/xfce4_panel_fixes_for_non_dark_themes.patch.txt); I'm not a themer and my CSS knowledge is limited, so you'll probably come up with a much better fix.
Thanks

**Comment by vinceliuice** [comment]
I'll fix it

**Comment by eworm-de** [comment]
I like the theme and would consider using it when it is fixed for Xfce... Any progress?

**Comment by eworm-de** [comment]
BTW, #9 is related.
