### ISSUE TITLE
No color accents in Cinnamon

### ISSUE THREAD

**Issue by 666xan666** [vinceliuice/Orchis-theme#480]
There are no accents at all in any theme. Tried every command from manual but not working.

OS: Linux MInt 22
DE: Cinnamon 6.2.9
WM: Muffin (X11)
WM Theme: Orchis-Green-Dark (Mint-Y)
Theme: Orchis-Green-Dark [GTK2/3/4]
Icons: Newaita-reborn-mint-dark [GTK2/3/4]

![Orchis](https://github.com/user-attachments/assets/32790c9c-ee04-4a0e-bd58-d093ebea3d8c)

**Comment by vinceliuice** [comment]
There is no colorful titlebar background version

**Comment by 666xan666** [comment]
Dear @vinceliuice in this case how this is possible? 
![465142356_10230760022957585_9187001703973607631_n](https://github.com/user-attachments/assets/8d1a3101-9274-4af7-94d8-86ee442c7f63)

**Comment by vinceliuice** [comment]
You are using Mint-Y-Teal WM theme not Orchis, Orchis only do not have such design

**Comment by Juan-Lutz** [comment]
The screenshot was made at 22:30 .... my QRedShiift app was running and make a cepia filter in the night. There was the "yellow* accent asked me. In any case a nice effect ( care for the eyes ;-)
