### ISSUE TITLE
Dark Theme Not Applied to Notification Banner

### ISSUE THREAD

**Issue by gitongaisaac** [vinceliuice/Orchis-theme#483]
First of all, thank you for creating this theme. I really appreciate the time and effort you’ve put into making such a visually appealing and functional design. I’m grateful for your hard work.

I use Ubuntu 24.04 with GNOME 46 and a dark theme. However, the notification banner does not fully adapt to the dark theme. Specifically:

The notification banner is light-themed (light background) even though the installed theme is dark. 

Even on the faulty theme:

The title, action buttons (close and expand buttons) and button text are not visible (light text on a light background).

This issue did not occur on my previous machine, where the theme worked as expected (had installed a few months ago). After switching machines, this problem appeared, so it's a recent issue.

![image](https://github.com/user-attachments/assets/ae0e283b-12ac-411b-9237-0aa6755d39a1)

**Comment by vinceliuice** [comment]
What about now ?

**Comment by gitongaisaac** [comment]
It works, thank you.
