### ISSUE TITLE
Some apps are dark in light theme

### ISSUE THREAD

**Issue by chilacayotito** [vinceliuice/Orchis-theme#486]
Hello! I recently updated the theme and some apps started appearing with a dark theme.
![imagen](https://github.com/user-attachments/assets/d51599b2-fde9-4b7e-98ab-212bc671ff2e)
(The app on the right had a light theme before I updated)

I installed the theme with this command:
```
./install.sh -t pink -c light -s standard -l --tweaks compact 
``` 

How can I make them all light again? Thanks in advance!

**Comment by vinceliuice** [comment]
Check `~/.config/gtk-3.0/settings.ini` and `~/.config/gtk-4.0/settings.ini` make sure `gtk-application-prefer-dark-theme=0`

**Comment by rishikoushikz** [comment]
hello uninstall and reinstall with this command bro this works for me `./install.sh -c  light -t pink --tweaks compact macos dock -l`
