### ISSUE TITLE
Ubuntu Software store in light theme after installing Orchis-dark with sudo 

### ISSUE THREAD

**Issue by meesterexx** [vinceliuice/Orchis-theme#49]
"Install this theme with sudo"

_Originally posted by @vinceliuice in https://github.com/vinceliuice/Orchis-theme/issues/47#issuecomment-748418179_

Thank you for the quick reply. Installed with sudo and Synaptics is fixed, but Ubuntu Software store is still in light theme. I tried rebooting and setting to Yaru-dark and back to Orchis -dark.

**Comment by axalox** [comment]
When you launch app with sudo you don't have same theme, you have to tweak

**Comment by vinceliuice** [comment]
You need install snap version
