### ISSUE TITLE
Color issues 

### ISSUE THREAD

**Issue by xpt1x** [vinceliuice/Orchis-theme#5]
Loved the theme :heart: 
Found out these issues :
![Screenshot-20200406123517-443x521](https://user-images.githubusercontent.com/33655587/78531567-4cfb6400-7803-11ea-8033-ca6ac470a04b.png)
![Screenshot-20200406123552-1119x434](https://user-images.githubusercontent.com/33655587/78531573-4ec52780-7803-11ea-9ded-ad7a3d5ad9d4.png)

**Comment by xpt1x** [comment]
Even after fix, its still the same in gnome
@vinceliuice

**Comment by xpt1x** [comment]
@vinceliuice the latest fix https://github.com/vinceliuice/Orchis-theme/commit/dfc417848b90714701f72fe98917ba92e64d2e73 doesn't seems to get these issues fixed in gnome

**Comment by vinceliuice** [comment]
But it works all well on my gnome-shell 3.36

**Comment by vinceliuice** [comment]
Did you changed the gdm theme?

**Comment by xpt1x** [comment]
Yeah it was replaced automatically when i install flat-remix theme by daniruiz

**Comment by vinceliuice** [comment]
Maybe that's the reason, gdm theme will overwrite some users gnome-shell theme style

**Comment by vinceliuice** [comment]
You can revert to default gdm theme and try again

**Comment by xpt1x** [comment]
I reverted back and now its fixed but still the wifi network selection submenu highlights in white, is it normal ?
Bcoz i see my dash search is fixed now

**Comment by vinceliuice** [comment]
Could you give a screenshot?

**Comment by xpt1x** [comment]
![Screenshot-20200408204336-411x407](https://user-images.githubusercontent.com/33655587/78801054-cba9fa00-79d9-11ea-8bb1-e18a8499ef0c.png)
![Screenshot-20200408204349-631x244](https://user-images.githubusercontent.com/33655587/78801067-ce0c5400-79d9-11ea-8b09-9aecbc55cc12.png)

Current screenshots ! After resetting GDM theme to that purple theme of ubuntu

**Comment by vinceliuice** [comment]
Don't worry, this is not bug, I.m purposely set to achieve the same appearance as chromeos

**Comment by xpt1x** [comment]
Ohh, then ok :smile: 
This materialistic look is just awesome :fire:

**Comment by vinceliuice** [comment]
Thank you!
