### ISSUE TITLE
waybar acting weird with orchis

### ISSUE THREAD

**Issue by parsarch** [vinceliuice/Orchis-theme#51]
waybar's workspace module gets a lot of padding on each workspace when orchis theme is applied,but it's ok with other themes,so I think that this issue is from orchis,not waybar

**Comment by vinceliuice** [comment]
Could you show me some screenshots?

**Comment by parsarch** [comment]
> Could you show me some screenshots?

yeah sure 
![image](https://user-images.githubusercontent.com/59556480/104118946-a4ee6a80-5341-11eb-94de-a670e451d498.png)
(with orchis)
![image](https://user-images.githubusercontent.com/59556480/104118959-b8013a80-5341-11eb-99db-9676a5f42fe9.png)
(with whitesur)

**Comment by parsarch** [comment]
Hi,It's been a while,any updates?

**Comment by memchr** [comment]
@parsarch 

After a bisection of `gtk.css`, I was able to find the rule (`button.text-button.flat min-width`) that causes this behavior

https://github.com/vinceliuice/Orchis-theme/blob/01a359ae6d9f1df79feb71f1fe6c02ee898043fd/src/gtk/3.0/gtk.css#L749-L753

However, this is not the issue with this theme, nor with the waybar.

You can override the `min-width' in waybar's style.css to migrate the problem.

e.g. 

```css
#workspaces button {
  min-width: 20px;
}
```
