### ISSUE TITLE
prompt: command not found

### ISSUE THREAD

**Issue by Obka** [vinceliuice/Orchis-theme#61]
hello
when i use `./install.sh` in  `src/gnome-shell/extensions/dash-to-panel` i have an error :

`
./install.sh: line 18: prompt: command not found
`

use sudo and without sudo but not work .

**Comment by vinceliuice** [comment]
I'll fix this!

**Comment by Obka** [comment]
But there is still another problem
![image](https://user-images.githubusercontent.com/13798815/110175101-74452180-7e16-11eb-8106-62eb8254be45.png)

**Comment by vinceliuice** [comment]
I'll check this

**Comment by lpoblet** [comment]
Had the same issue with **stylesheet.css not exist!**. Solved by copying the files manually following the script. 
Not sure why the folder name in **install.sh** has this "@jderose9.github.com" but I removed it as it sounds like it shouldn't be there @vinceliuice

**Comment by embrom** [comment]
> Had the same issue with **stylesheet.css not exist!**. Solved by copying the files manually following the script.
> Not sure why the folder name in **install.sh** has this "@jderose9.github.com" but I removed it as it sounds like it shouldn't be there @vinceliuice

how u solved it?, which files did u copy

**Comment by mshzsh** [comment]
@embrom 
Go to "src/gnome-shell/extensions/dash-to-panel" and use following commands for root user :

`mkdir -p /usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com`
`cp ./* /usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com`

or following commands for non root users :

`mkdir -p $HOME/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com`
`cp ./* $HOME/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com`

then use ./install.sh

**Comment by nikbakhtsaeid** [comment]
I have this problem and I do what you said. But it did not work!

**Comment by icetick** [comment]
> I have this problem and I do what you said. But it did not work!

There can be different versions/contributors of dash-to-dock extension.
Basically to solve this issue check your destination path for dash-to-dock by: 
ls ~/.local/share/gnome-shell/extensions/
You will get directories of installed gnome-shell extensions
Change line in install.sh with "destination directory" to your dash-to-dock actual directory (for me missing part was
![Screenshot from 2021-12-13 12-49-52](https://user-images.githubusercontent.com/22273541/145799448-30346f9c-2557-4783-8e41-9191735f4363.png)
 dash-to-dock@micxgx.gmail.com)

**Comment by vinceliuice** [comment]
You must install dash to panel first

**Comment by david-chemwetich** [comment]
You must install dash to panel first
then user sudo ./install.sh

**Comment by clamsfeel2** [comment]
@mshzsh I am trying to do what you said, but for some reason it is not working. Won't even create a directory. I can, however, use gui and copy the directory that way. Although, that doesn't seem to fix anything and I am getting the same `stylesheet.css not exist!` error. Any ideas?

**Comment by vinceliuice** [comment]
It's no need to install this anymore, dash to panel issues fixed
