### ISSUE TITLE
GNOME Terminal Rezise bug

### ISSUE THREAD

**Issue by DevC512L** [vinceliuice/Orchis-theme#65]
Ok, this is weird and I don t know if this problem is caused by the theme, or is simply triggering it in Gnome Terminal or GNOME Shell.
Info:
DE: GNOME 3.38 and 40
OS: Fedora 33,34 and Ubuntu 20.10
Display Server: Wayland (Xorg not tested but I think its affected too)

- Happens only with Orchis theme in any variant applied. Other GTK themes seem to work fine (tried Materia and Adwaita).
- Happens with and without Gnome extensions enabled
- Only in Gnome Terminal. Other apps work fine

Steps to reproduce:
1. Apply Orchis theme with gnome-tweaks
2. Launch  Gnome terminal
3. Maximize it
4. Unmaximize it
5. Gnome terminal unmaximizes but does not recover its original window size

**Comment by alvarengav** [comment]
same problem
