### ISSUE TITLE
Buttom radius corner for all windows

### ISSUE THREAD

**Issue by Faetu** [vinceliuice/Orchis-theme#66]
Hi

First: I love your theme! Its the best theme.

Now to my "problem"/question:

Some applications like "Nautilus" or the gnome-settings, have bottom corner with radius.
But others like "Gnome-Terminal" dont have radius on the bottom corner. Why? And are there a way to change that?
And can I have also to electron apps like "VS Code" bottom corners with radius?

best regards

**Comment by Faetu** [comment]
Here what i mean:

![corners](https://user-images.githubusercontent.com/55803495/111818713-c9396b00-88df-11eb-80dc-503611f45344.png)

**Comment by vinceliuice** [comment]
Terminal can not set bottom rounded coners! because it has a terminal emulation layer is on top, this is not gtk theme to control!
