### ISSUE TITLE
Gnome 40: Several issues.

### ISSUE THREAD

**Issue by Icy-Thought** [vinceliuice/Orchis-theme#71]
Firstly, I appreciate the effort you've put into this wonderful theme! Keep up the amazing work!

These are the several issues I found after I had upgraded to Gnome 40:

**1. Gnome Extensions won't apply Orchis theme after having set both `Applications: Orchis-dark-compact` and `Shell: orchis-dark-compact` (same applies for the other Orchis variants).**

_Orchis-dark-compact:_ 
![Screenshot from 2021-04-07 16-05-39](https://user-images.githubusercontent.com/53710398/113879771-2a57ae80-97bb-11eb-9db1-8f6f7f93f3a7.png)

_Adwaita-dark:_ 
![Screenshot from 2021-04-07 16-02-41](https://user-images.githubusercontent.com/53710398/113879660-098f5900-97bb-11eb-8f86-4c8c8193ed48.png)

**2. Workspace Indicator displayed in the activity tab is not displayed properly:**

_Orchis-dark-compact:_ 
![Screenshot from 2021-04-07 15-59-31](https://user-images.githubusercontent.com/53710398/113879040-71916f80-97ba-11eb-9a4c-2c94122cea20.png)

_Adwaita-dark:_ 
![Screenshot from 2021-04-07 16-00-37](https://user-images.githubusercontent.com/53710398/113879371-bf0ddc80-97ba-11eb-83c7-60c5a258bfaa.png)

**3.  Application dock found in the `activity tab` displays two docks instead of one.**

_Orchis-dark-compact:_ 
![Screenshot from 2021-04-07 15-59-17](https://user-images.githubusercontent.com/53710398/113879415-c92fdb00-97ba-11eb-8667-9c5cab419f28.png)

_Adwaita-dark:_ 
![Screenshot from 2021-04-07 16-00-42](https://user-images.githubusercontent.com/53710398/113879437-cdf48f00-97ba-11eb-86e4-18f7dd4f600c.png)

**4. Title bar of `Gnome-Tweaks` is not displayed.**
_Orchis-dark-compact:_ 
![Screenshot from 2021-04-07 16-00-17](https://user-images.githubusercontent.com/53710398/113879466-d4830680-97ba-11eb-8003-cc09372794c8.png)

_Adwaita-dark:_ 
![Screenshot from 2021-04-07 16-13-24](https://user-images.githubusercontent.com/53710398/113880900-33954b00-97bc-11eb-81d1-7316998a6e6c.png)

**Comment by y-usuzumi** [comment]
Was just about to post the same bug report. Thanks!

**Comment by vinceliuice** [comment]
Still working on it, Gnome 40.0 changed a lot I have a lots work to do, just wait, it'll be all fixed

**Comment by Icy-Thought** [comment]
I would've contributed if I had the knowledge to do so, unfortunately this is all I can do at the moment. 

Good luck and appreciate the work!

**Comment by HideyoshiNakazone** [comment]
So the Orchis GTK Theme will be ported to gtk4?

**Comment by Thorge2** [comment]
@HideyoshiNakazone He will, he stated that in this comment [https://github.com/vinceliuice/ChromeOS-theme/issues/31#issuecomment-812797206](url)

**Comment by vinceliuice** [comment]
Fixed!
