### ISSUE TITLE
White text on white firefox theme.  

### ISSUE THREAD

**Issue by zramos2** [vinceliuice/Orchis-theme#73]
Anyone know how to fix this? This also applies with Orchis, Orchis-Compact, Orchis-light, and Orchis-light-compact.  It's hard to type out a website too because the text is white.  

![Screenshot from 2021-04-12 21-15-07](https://user-images.githubusercontent.com/36197897/114486957-5b2d4e80-9bd4-11eb-8f01-968e4ac0839b.png)

**Comment by vinceliuice** [comment]
It's that a firefox theme issue or gtk theme issue？

**Comment by zramos2** [comment]
gtk theme issue.  I switched to Orchis-dark and it's working fine.  Only once when I switch to the white theme it doesn't correct itself.

**Comment by vinceliuice** [comment]
I get it, I'll fix this

**Comment by vinceliuice** [comment]
What's your firefox version, I did not find this issue on my firefox 87

**Comment by vinceliuice** [comment]
![2021-04-13 11-17-17 的屏幕截图](https://user-images.githubusercontent.com/7604295/114491816-de3cbc00-9c49-11eb-863f-dd73cb0c872b.png)

**Comment by zramos2** [comment]
Currently using version 87.0
![Screenshot from 2021-04-12 22-20-57](https://user-images.githubusercontent.com/36197897/114492083-6a64ca00-9bdd-11eb-9fe6-ccad4dc6f1ea.png)

**Comment by vinceliuice** [comment]
Then it should be ok, I didn't find any issue on my firefox 87

**Comment by zramos2** [comment]
Fixed it! On the Firefox `Customize Toolbar...`. Make sure you're `theme` is **NOT** `Dark`. Make sure it's either `Default` or `Light`.
![Screenshot from 2021-04-12 22-44-15](https://user-images.githubusercontent.com/36197897/114493884-f9271600-9be0-11eb-9dfc-cd9ef71d91cf.png)

**Comment by zramos2** [comment]
Thanks for the speedy replies! :)

**Comment by vinceliuice** [comment]
You are welcome!
