### ISSUE TITLE
Firefox dark theme

### ISSUE THREAD

**Issue by HazilMohamed** [vinceliuice/Orchis-theme#74]
Hi, Is it possible to enable dark theme for firefox on Orchis Light theme.

**Comment by vinceliuice** [comment]
After you install this theme, open the `userChrome.css` file and delete `/*` before @import `"Orchis/theme-dark.css"; /**/` to use the dark theme!
![Uploading 2021-04-14 13-51-06 的屏幕截图.png…]()

**Comment by vinceliuice** [comment]
Download the last update of github
