### ISSUE TITLE
Firefox theme, use gtk theme title buttons?

### ISSUE THREAD

**Issue by bmreading** [vinceliuice/Orchis-theme#75]
Is there a way to disable the custom title buttons, and just use the buttons of the GTK theme?

**Comment by vinceliuice** [comment]
Need to modify this `../chrome/Orchis/parts/icons.css` file
Delete line 152 `/* Window buttons */ ...` to liine 174  and line 371 to line 393

**Comment by vinceliuice** [comment]
And then you need to modify `../chrome/Orchis/theme.css`
Delete line 5 `@import "parts/csd.css";`

**Comment by vinceliuice** [comment]
Then it'll show default gtk theme titlebuttons

**Comment by bmreading** [comment]
Awesome! That works, but I do get the sharp corners now. I guess there's no way to fix that? 
![Screenshot from 2021-04-15 03-34-40](https://user-images.githubusercontent.com/48337326/114839682-ab0a4200-9d9b-11eb-91f3-f6bd4c51bca2.png)

**Comment by vinceliuice** [comment]
CSD have sharp corners

See upstream bug.
Wayland fix:

    Go to the about:config page
    Search for the layers.acceleration.force-enabled preference and set it to true.
    Now restart Firefox, and it should look good!

X11 fix:

    Go to the about:config page
    Type mozilla.widget.use-argb-visuals
    Set it as a boolean and click on the add button
    Now restart Firefox, and it should look good!

**Comment by bmreading** [comment]
Unfortunately, neither of those fixes work for me. I'm on X11, and had rounded corners before making the changes. Maybe it's not the same issue?

**Comment by vinceliuice** [comment]
Then you need to make sure the gtk theme have tge same windows boder-radius as orchis, because firefox will have a gtk window widget bottom

**Comment by bmreading** [comment]
Thank you. That's all that I needed to know. I definitely appreciate the work you've put into this project.

**Comment by vinceliuice** [comment]
And this fix is only works on gnome, kde is not work

**Comment by bmreading** [comment]
I wanted to update this with a solution to the particular problem I was having. I needed to go to Preferences > Extensions & Themes > Themes, and choose the Default theme. That fixed the sharp corners for me.
