### ISSUE TITLE
Pling version is newer than the version on gh

### ISSUE THREAD

**Issue by b-reich** [vinceliuice/Orchis-theme#77]
There is no tag that matches the version on [Pling](https://www.pling.com/p/1357889). It is easier to roll out when there are matching tags.

example AUR https://aur.archlinux.org/packages/orchis-theme-git/

**Comment by vinceliuice** [comment]
I add a new release now

**Comment by b-reich** [comment]
@vinceliuice thanks! It would be great if its update more often. Together with the version at Pling.

**Comment by vinceliuice** [comment]
No problem!
