### ISSUE TITLE
This theme is out of step with the nautilus layout.

### ISSUE THREAD

**Issue by gesangtome** [vinceliuice/Orchis-theme#8]
Tested on fedora 32.

Now the layout looks something like this. I am not competent enough to submit the patch. I like this theme very much. Hopefully this will be fixed.

![2020-04-29 08-25-31 的屏幕截图](https://user-images.githubusercontent.com/9876749/80550697-7b7bf180-89f3-11ea-90f9-2448f569434e.png)

**Comment by xpt1x** [comment]
Can't u just grab it and resize it ?
Coz i can do that in ubuntu20

**Comment by gesangtome** [comment]
> Can't u just grab it and resize it ?
> Coz i can do that in ubuntu20

I don't know how to modify the CSS.

**Comment by vinceliuice** [comment]
你是说左边太宽了吗？

**Comment by gesangtome** [comment]
> 你是说左边太宽了吗？

是啊，看上去很不协调，而且选中项目的颜色怪怪的

**Comment by xpt1x** [comment]
if u think left side is too wide, then just drag it and set it back to normal. 
And for colors i don't think its off, its proper actually !
Selected item is already darker, it appears in blue which separates itself from others

**Comment by vinceliuice** [comment]
这个直接用鼠标调一下就行啦，拉住左边栏往右一点的白色区域就可以调节，往左拉
