### ISSUE TITLE
Shadowing Issue

### ISSUE THREAD

**Issue by b-reich** [vinceliuice/Orchis-theme#82]
I got some weird shadows.

![image](https://user-images.githubusercontent.com/1573025/116209508-460efe80-a742-11eb-915c-ea538e635e25.png)

Installed Version: latest from Repo
Running on GNOME 40.1 on Arch

**Comment by vinceliuice** [comment]
Did you installed any gdm theme?

**Comment by b-reich** [comment]
Nope, I just use the GTK and Gnome Shell Theme.

**Comment by b-reich** [comment]
the latest update from arch or the repo fix this issue
