### ISSUE TITLE
Submenus in the shell theme do not follow dark mode

### ISSUE THREAD

**Issue by K4LCIFER** [vinceliuice/Orchis-theme#97]
When set to a dark theme in the orchis shell, the submenus are white. 

For example, with a dark menu selected, go to the system menu in the top right of the title bar and select a drop down menu like the network menu and observe that the background is white instead of a dark mode dark color.

**Comment by vinceliuice** [comment]
Could you give me some screenshot?

**Comment by K4LCIFER** [comment]
@vinceliuice Sure
![image](https://user-images.githubusercontent.com/7829231/120901486-16c89880-c5f0-11eb-87a9-655182b296d7.png)

**Comment by vinceliuice** [comment]
this is an intended design (like the chromeos) not a issue

**Comment by MikeMoolenaar** [comment]
I'm personally not a huge fan of this design, luckily it's quite easy to edit.
(I know you are supposed to edit the SCSS file and then compile, but this is just a dirty edit)

So for anyone who wants to make the white submenu dark:
- Go to `~/.themes` and make a copy of the `Orchis-dark` theme folder, name it something like `Orchis-dark-custom`.
- Go into the newly copied folder and then into `gnome-shell`, replace the `gnome-shell.css` file with this one I made ([Gist](https://gist.github.com/MikeMoolenaar/36f4cc1cab7d1ffe013c97ff2614c7aa) / [Gist raw](https://gist.githubusercontent.com/MikeMoolenaar/36f4cc1cab7d1ffe013c97ff2614c7aa/raw/e260ed238e81ba23845a79f928979ce2a145af46/gnome-shell.css))
- Then go into gnome tweaks and change the shell theme to `Orchis-dark-custom`

I made the edits roughly between line 965 and 1041.

**Comment by hugeblank** [comment]
@MikeMoolenaar thank you so much for this!

**Comment by Movisivi** [comment]
> I'm personally not a huge fan of this design, luckily it's quite easy to edit. (I know you are supposed to edit the SCSS file and then compile, but this is just a dirty edit)
> 
> So for anyone who wants to make the white submenu dark:
> 
>     * Go to `~/.themes` and make a copy of the `Orchis-dark` theme folder, name it something like `Orchis-dark-custom`.
> 
>     * Go into the newly copied folder and then into `gnome-shell`, replace the `gnome-shell.css` file with this one I made ([Gist](https://gist.github.com/MikeMoolenaar/36f4cc1cab7d1ffe013c97ff2614c7aa) / [Gist raw](https://gist.githubusercontent.com/MikeMoolenaar/36f4cc1cab7d1ffe013c97ff2614c7aa/raw/e260ed238e81ba23845a79f928979ce2a145af46/gnome-shell.css)).
> 
>     * Then go into gnome tweaks and change the shell theme to `Orchis-dark-custom`.
> 
> 
> I made the edits roughly between line 965 and 1041.

Is there a compact version of this?

**Comment by Demetrio92** [comment]
edit `src/gnome-shell/sass/widgets/_popovers-42.scss` for a permanent fix

**Comment by Demetrio92** [comment]
@everyone see PR above. Come and test it, especially if you're on gnome below 42
