### ISSUE TITLE
Firefox theme breaks with many tabs open

### ISSUE THREAD

**Issue by TheCultLeader666** [vinceliuice/Orchis-theme#99]
When you open enough tabs to have the close button on background tabs disappear, the text and favicons get strangely justified to the right. I assume this is because the close button is gone and the text moves over to where the close button was.
![image](https://user-images.githubusercontent.com/65368815/120905055-13103280-c63f-11eb-9424-7d109718494c.png)
In addition, when you open enough tabs to invoke the sideways tab scrollbar, the movement arrows are unnaturally small
![image](https://user-images.githubusercontent.com/65368815/120905071-31762e00-c63f-11eb-93c3-a235ba247cb3.png)

**Comment by hugeblank** [comment]
I've found that this issue occurs with literally just one tab open:
![image](https://user-images.githubusercontent.com/16393543/140833718-07910451-4cda-4955-817f-2d56ce362190.png)
